### ISSUE TITLE
www.kiwix.org welcome page does not display properly on my iPad

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#100]
The background image is not displayed at all. Therefore part of the text is white on white and almost not visible. I don't think this is a recent problem/regression. Problem occurs on Safari and Firefox (ar least).

![37EC17B3-35A7-4E49-B101-BE423E3717F4](https://user-images.githubusercontent.com/1029718/70387071-e96e4080-19a0-11ea-9065-aa98027d2f5b.png)

**Comment by arunava001OS** [comment]
Hello ,
I would like to address this issue "www.kiwix.org welcome page does not display properly on my iPad #100" but I am not sure which file is the homepage html document for the website.

**Comment by kelson42** [comment]
@arunava001OS This is a problem for the web site admins. You won't be able to fix except if you can explain from the browser side what goes wrong.

**Comment by martin8032** [comment]
As far as I can tell this problem occurs only with Safari on iPadOS (not with Safari on iOS or macOS, not with Chrome on iPadOS). And I can see the same problem with some other websites built with the Divi theme.

To spend not too much time on this, I simply changed the text color. This should ensure sufficient contrast with any browser/device. Hopefully Elegant Themes fixes the Divi theme and we can switch back to the original design in the near future.
