### ISSUE TITLE
Better show what is going on, on www.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#101]
In an attempt to put a bit of dynamic news on www.kiwix.org I propose to show what is going on Twitter on www.kiwix.org. Showing the N last tweets might be a bit much... but displaying the pinned tweet would allow us to do that in a more controlled manner.

**Comment by Popolechien** [comment]
Not a big fan of these widgets

**Comment by martin8032** [comment]
If we only want to show selected tweets on kiwix.org anyway, why not simply publish this information directly on our website as standard WordPress posts?

**Comment by kelson42** [comment]
@martin8032 Probably doable, it's just manual/maintenance work. If someone wants to volunteer for that... Good for me.

**Comment by martin8032** [comment]
I can provide the technical solution – be it a Twitter widget, be it a WordPress news section. However, I don't have the time to publish news on a regular basis.

**Comment by kelson42** [comment]
@martin8032 This is why I assumed that we have to use an extension if we want to do it (but I don't have found a free extension for displaying only pinned tweets).
@Popolechien Should we close this ticket if you are against? You disagree with the idea of @atgomez to bring a bit of news/dynamic within the Web site... or maybe you have an alternative proposal?

**Comment by Popolechien** [comment]
Oh I'm all for being dynamic. We simply do not have the resources and I can't think of any website that displays tweets on top of its messaging and looks good. I'd rather keep these channels separate as long as there isn't a clearly thought-out strategy for that.

**Comment by atgomez** [comment]
FWIW I don't think having the twitter feed on the website is a critical
piece. It's good to have some tweets that are active and show random
internet browsers that Kiwix isn't just a dead webpage, but it's this
particular thing isn't the only way to do that.
