### ISSUE TITLE
Alignment of new logos

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#102]
I've uploaded the logo of two recent sponsors/awards we won (hundrED and Mozilla) yet they seem quite off (Mozilla misaligned and hundrEd probably a tad too big). There aren't too many options to play with and I can't seem to be able to fix it. @martin8032 Any idea?

**Comment by martin8032** [comment]
@Popolechien All logos must be 600 x 400 (W x H) and include the surrounding white space (this allows you to adjust the logo size without messing with the logo alignment). See example below.

![logo_example](https://user-images.githubusercontent.com/7620141/70795147-751c0e80-1d9f-11ea-94a6-d1e3a3bc378d.png)
