### ISSUE TITLE
Make dedicated instance of kiwix-serve for KaiOS

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#103]
For Wikimed in English. Subdomain will be https://en.wikimed.kaios.kiwix.org/

**Comment by kelson42** [comment]
@Popolechien OK for you? With that we should be definitly OK for KaiOS?

**Comment by Popolechien** [comment]
@kelson42 sounds like a good idea, but why not simply en.wikimed.kiwix.org? There is no design element that is specific to KaiOS and we may be / may have to use it for some other project someday.

**Comment by kelson42** [comment]
@Popolechien OK, to me.

**Comment by kelson42** [comment]
Implementing this shows me that this long standing feature would be really needed heere https://github.com/kiwix/kiwix-tools/issues/53

**Comment by kelson42** [comment]
Done https://en.wikimed.kaios.kiwix.org
