### ISSUE TITLE
Setup and manage Google free adds

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#105]
This is probably one of the cheapest solution to increase awareness and audience for our apps and contnents. We should setup this ASAP.

**Comment by martin8032** [comment]
The account is up and running. However, creating campaigns and landing pages is time-consuming. And in the end we still need the final approval by Google.

**Comment by Popolechien** [comment]
I'm all for having a trial run, but this campaigning "money" should utlimately go towards advertising our pre-made, for sale Wikipedia Raspberry images.

**Comment by martin8032** [comment]
@Popolechien See my mail.

**Comment by kelson42** [comment]
Any news on that front? We could link our Google Ads account with our Android developer account would bring certain advantages, see https://support.google.com/googleplay/android-developer/answer/6110967. Could someone please give me our Google Adds account number?

**Comment by kelson42** [comment]
@martin8032 We can create Google Ads campaign for (one of) our Android app easily (looks like) from the Google Play Admin Console (menu "User Acquisition" > "Promoting" - my translations from my UI in French). Do you see it? It might be easier that way to create straight advert. fro our "WikiMed - Offline Medical Wikipedia" app.

**Comment by martin8032** [comment]
@kelson42 I am setting up the campaign for WikiMed currently. We still need the approval by Google, and I don't think we are ready for this yet. (BTW: You should never ever use the words «easy» and «Google Ads» in the same sentence!) Our most recent problem is that we are not allowed to use the word «Wikipedia» in our ads. @Popolechien is contacting WMF for an approval.

**Comment by martin8032** [comment]
@kelson42 Do I have access to our Google Play Admin Console? Through which account?

**Comment by kelson42** [comment]
@martin8032 I strongly suspect I should invite you to the Google Play Console. If you agree, please tell me which email should be invited.

**Comment by kelson42** [comment]
> Our most recent problem is that we are not allowed to use the word «Wikipedia» in our ads

We can perfectly IMO do advertisement without this keyword. The trademark topic with the WMF is running since years already... and it could take additional years to be closed. You confirm this is not a blocker?

**Comment by kelson42** [comment]
> @kelson42 Do I have access to our Google Play Admin Console? Through which account?

I have send you an invitation and you should have access straight. What is unclear to me is if you have access to:
* the link to start "quickly" with Google Ads campaign
* The associated accounts to make a link with our Google Ads Account (number)

**Comment by Popolechien** [comment]
I was going to recommend that for the Wikimed ad we skip the Wikipedia word entirely. It's rather secondary, in the end. But we'll need to get that trademark agreement sorted sooner rather than later (if only for the pre-packaged Raspberry images).

**Comment by kelson42** [comment]
@martin8032 @Popolechien I have heard this works now.... without more details, What is the status and next steps?

**Comment by martin8032** [comment]
It worked for the Swiss Laos Hospital Project. It was a pain, and it took me weeks to figure everything out. I think I have most of the necessary knowledge know, but it would still be a lot of work to set everything up for Kiwix, and at the moment I have very limited resources for volunteer work. But I could brief someone else if necessary.

**Comment by kelson42** [comment]
@martin8032 As long as this knowledge is fresh, yes this is really important you share it. I'm not exactly sure where is the complexity but I would recommend to:
* write a small documentation with the most critical things to know
* secure @Popolechien or/and @siemsie can launch adds campaign.

@siemsie @Popolechien Maybe a good reason to visit us again in Zurich ;)

**Comment by martin8032** [comment]
In a nutshell:

- You need to set up proper conversion tracking.
- You can only link to your own website (not Facebook, not YouTube…).
- You can only use search ads (no ads on the Google Display Network GDN).
- You need a good website (content, structure, performance) as in SEO.
- You need to reach 5% CTR (average over all campaigns in your account), so you really have to care about relevant ads and relevant content on the landing page.
- You need to update your ad account at least every 90 days.
- Make use of extensions and responsive ads.
- You must set proper geo-targeting.
- You need at least 2 active ad groups per enabled campaign, at least 2 text ads per enabled ad group, and at least 2 unique sitelink ad extensions.
- You are not allowed to use single-word keywords, generic keywords, and no keywords with a quality score below 3.

**Comment by kelson42** [comment]
@Popolechien @siemsie Can/will one of you secure this?

**Comment by Popolechien** [comment]
We can look it up but I will certainly have some questions as a couple of concept are entirely new to me.

**Comment by kelson42** [comment]
@Popolechien @siemsie Should we close this ticket?

**Comment by Popolechien** [comment]
Yup.
