### ISSUE TITLE
Consistent name for XXX

### ISSUE THREAD

**Issue by martin8032** [kiwix/web#106]
On the page https://www.kiwix.org/de/downloads/kiwix-hotspot/ we are talking about an «online installer» – but if you click the link you get to the «cardshop». We need one single term and use it consistenly. Personally, I don't like «online installer» – i'd rather call it «card configurator» (or «card shop»).

**Comment by Popolechien** [comment]
I agree. Even _hotspot configurator_ or _maker_ could do. I'd like the name to tell it like it is. _Cardshop_ is also good enough for the time being. I've renamed it so - we can close the ticket.

**Comment by martin8032** [comment]
To me it looks more like you have deleted the English page: https://www.kiwix.org/en/downloads/kiwix-hotspot/

**Comment by Popolechien** [comment]
@martin8032 Ah, I was about to write asking you the same thing!

**Comment by martin8032** [comment]
@Popolechien Can you fix it?

**Comment by Popolechien** [comment]
@martin8032 Nope, I can't see any history. Could it be that it got deleted during the translation process?

**Comment by martin8032** [comment]
@Popolechien Wait – did you update the EN or the DE version of the page?

**Comment by Popolechien** [comment]
@martin8032 I changed one word on the DE version, then when I wanted to do the same on the EN version could not find it.

**Comment by martin8032** [comment]
You should NEVER update translated version of the site directly. Update the original (English), then go through the translation process as shown in our video. Everything else can break the site.

**Comment by Popolechien** [comment]
Dammit - so I did mess up. Sorry :-(
There was a warning from WPML asking that I go through the translation interface but I obviously misunderstood their prompt. Well, that's a learning :-/

**Comment by Popolechien** [comment]
To my credit I did Wikimed right.

**Comment by martin8032** [comment]
That Hotspot page is really messed up. I did not find a way to restore it, so you probably have to rebuild it from scratch. At least I could retrieve the content and export it as a Word document (see your mail inbox).

**Comment by Popolechien** [comment]
Yeah that's odd. Content received, am on it. Thanks.

**Comment by Popolechien** [comment]
Ok so I've re-created the page and the DIVI builder wouldn't save - or rather, it re-deleted the layout when I updated the page. @martin8032 should/can we delete and recreate the page to make a clean start?

**Comment by martin8032** [comment]
Don't delete anything, but create a fresh page in the ENGLISH version of the website with the content from the Word file and let me know when you're done. I'll take care of the rest.

**Comment by Popolechien** [comment]
Here we go:
https://www.kiwix.org/en/hotspot/

FWIW I copied the layout of an existing Kiwix-hotspot page and all the updates we'd made were in (ie, I didn't even have to re-insert the text). Yet the same page I cloned from remains empty when looking at it directly (the new page is fine).

**Comment by martin8032** [comment]
I've cleaned things up. You have to redo the FR translation though. See your inbox for a Word document with the french text from the old page.

**Comment by Popolechien** [comment]
Done. The fields were all correctly pre-filled though: not automated translation, but the corrections I had already done last time. Did you do it, or is there some dark magic happening there?

**Comment by martin8032** [comment]
I am not 100% sure, but that was probably the magic of the translation memory.

But more importantly: I don't see your translation, neither in the frontend nor in the backend. Do you?

**Comment by Popolechien** [comment]
Ok, had to redo it 0_o
Here: https://www.kiwix.org/fr/hotspot-kiwix/
