### ISSUE TITLE
use https for downloads (also redirections)

### ISSUE THREAD

**Issue by automactic** [kiwix/web#11]
Apple is starting to enforce all https traffic in app ~~starting Jan 1, 2017~~ [some time in the future](https://developer.apple.com/news/?id=12212016b). That means all download links **and** all redirections should use https. Failing to do so will result in app not able to pass App Store review.
Note: Apple do allow developers to provide a list of 3rd party domains they don't have control of as exceptions. This could be an alternative solution.

**Comment by Popolechien** [comment]
@kelson42 @automactic All links to itunes domain are https. But does this mean that the whole website should be https as well?

**Comment by kelson42** [comment]
@Popolechien it's only for download.kiwix.org and mirrors, does not mean http is also provided.

**Comment by kelson42** [comment]
@automactic what is the status on this? I have switched most of the mirrors to https when it was possible. That said as long as we have the old xulrunner based kiwix-desktop app in our portfolion, we can not switch all of them to HTTPS (because the truststore of xulrunner can not be updated).

**Comment by kelson42** [comment]
I close that ticket for the moment, @automactic if you still face problems then reopen it.
