### ISSUE TITLE
Allow Bitcoin donation

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#111]
If this is not too much a hassle to setup, this might be worth a try IMO. Maybe start with https://btcpayserver.org/ evaluation.

**Comment by NicolasDorier** [comment]
Happy to know, I am the main maintainer of the project. Don't hesitate to ping us on https://chat.btcpayserver.org/ or ping me on twitter if you have question or issues.

**Comment by kelson42** [comment]
Considering the excessive amount of energy needed by BTC, it sounds simply not reasonable to following this path to me.

**Comment by Popolechien** [comment]
We had a grand total of three offers to donate crypto over the past couple of years, but most importantly this does not fit with our general ambition of being carbon neutral.
@kelson42 Close ticket?

**Comment by alexk111** [comment]
> Considering the excessive amount of energy needed by BTC

What is this conclusion based on? Who defines the "excessive" amount?

> being carbon neutral

Who and how defines the standard of "carbon neutrality"? What if they tell you that there is an excessive amount of people that should stop breathing to be carbon neutral?

**Comment by kelson42** [comment]
> > Considering the excessive amount of energy needed by BTC
> 
> What is this conclusion based on? Who defines the "excessive" amount?

In comparison to other (usual) money transfer solutions. See https://en.wikipedia.org/wiki/Bitcoin#Energy_consumption_and_carbon_footprint

**Comment by NicolasDorier** [comment]
Seems like outdated article out there, china banned bitcoin mining completely this year.

**Comment by Popolechien** [comment]
> Seems like outdated article out there, china banned bitcoin mining completely this year.

If only there was a way to know why they did it:
https://www.coindesk.com/policy/2021/07/09/why-chinas-ban-on-crypto-mining-is-more-serious-than-before/

At this stage there have been more people who came out of nowhere in two days to downvote our decision not to accept Bitcoin than there have _ever_ been offers to donate in crypto over the past 4 years. 

The economics (and the vibe) do not make a compelling case, sorry ¯\_(ツ)_/¯
