### ISSUE TITLE
Make our wiki's wikitables sortable

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#120]
Following a bunch of comments on reddit, it would be nice if tables would be sortable one way or the other, most specifically [Template:ZIMdumps](https://wiki.kiwix.org/wiki/Template:ZIMdumps). I tried to edit the wikicode but I suspect we have an older version of mediawiki and it did not recognize it.

**Comment by kelson42** [comment]
I don't plan to invest anytime on this. This is a bit of work and not the right path.

**Comment by Popolechien** [comment]
Ongoing Kiwix-serve revamp is making the request kind of moot (or at least duplicate).
