### ISSUE TITLE
Update custom apps list on website

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#121]
* Kiwix JS WikiMed: https://www.microsoft.com/store/apps/9PHJSNP1CZ8J 
   (Full English WikiMed)
 * Kiwix JS Wikivoyage:
   https://www.microsoft.com/store/apps/9N5SB90Q4JBJ  (Full English
   Wikvoyage)
 * Kiwix JS WkikMed Electron (for Windows 7/8/10):
   https://kiwix.github.io/kiwix-js-windows/wikimed-electron.html (for
   Win 7/8/10 32bit or 64bit)

**Comment by kelson42** [comment]
@Popolechien Any chance to implement/close this ticket?

**Comment by Popolechien** [comment]
Done.
