### ISSUE TITLE
Replace all outbound HTTP links with HTTPS

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#126]
If possible at all....

Because of https://www.ghacks.net/2020/10/08/chrome-is-blocking-downloads-here-is-why/

**Comment by Popolechien** [comment]
Done at website level but here is the error message I get in the Chrome console
`Mixed Content: The site at 'https://www.kiwix.org/' was loaded over a secure connection, but the file at 'https://mirror.download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64_2.0.5.zip' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.`

**Comment by kelson42** [comment]
@Popolechien Work better now?

**Comment by Popolechien** [comment]
Yup!
