### ISSUE TITLE
Move to SHA256 checksums

### ISSUE THREAD

**Issue by dblueman** [kiwix/web#128]
The ZIM files have a MD5 checksum we can download, however MD5 is susceptible to collisions. Moving to SHA256 protects against this, which is the current standard.

**Comment by kelson42** [comment]
Agree on the principle, but are we talking about the wiki content pages? Or about something else?

**Comment by kelson42** [comment]
@dblueman Can you please confirm?

**Comment by kelson42** [comment]
Done
