### ISSUE TITLE
meta4 information is missing for recent ZIM files from download.kiwix.org

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/web#129]
Kiwix JS Windows relies on access to the .meta4 information provided by download.kiwix.org for each of its ZIM files. However, for the last month or so, this information is no longer available. For example, https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_maxi_2020-12.zim.meta4 returns 404 Not Found. Earlier ZIM archives have a .meta4 link, some of which can still be accessed, but it is as if the server is no longer creating this information for recent ZIM archives.

Can this meta page be restored for all ZIMs, or at least for future ZIMs? Is it a server configuration issue?

**Comment by kelson42** [comment]
@Jaifroid We have a platform problem since now a few weeks. download.kiwix.org is not reliable anymore like it was. We are working on it.

**Comment by kelson42** [comment]
I have configured monitoring on this and after tweaking a few things it seems to be OK for now. That said we will need to make more infrastucture work to stop having performance issue with this service. This planned for January. See https://github.com/kiwix/maintenance/issues/154. Nothing more to do for this ticket. Please reopen if new problem.
