### ISSUE TITLE
Question : From where the user can download old versions of Kiwix?

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/web#131]
For example, a user can download old versions of **LibreOffice** from the official website: 
**http://downloadarchive.documentfoundation.org/libreoffice/old/**

And does **Kiwix** have an official page where **old versions** are presented: ***. exe**, ***. appimage**?

**Comment by kelson42** [comment]
@Ubuntu-2020 All the software releases are available at https://download.kiwix.org/release/
