### ISSUE TITLE
Implement CAPTCHA on kiwix.org's contact form

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#133]
We've had more than 350 messages over the past 6 hours :-/
(They've stopped coming but who knows when they'll be back)

**Comment by martin8032** [comment]
I have implemented reCAPTCHA.

This might affect the website's compliance with GDPR and other data privacy laws. I have added a paragraph in our privacy policy, but I can not tell if this is sufficient.

**Comment by Popolechien** [comment]
Awesome, thanks.
