### ISSUE TITLE
Update mediawiki logo on our wiki

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#135]
See [announcement](https://lists.wikimedia.org/pipermail/wikitech-l/2021-March/094403.html?fbclid=IwAR0IPYITcjzfOpQHjFjbnBWW1tftP1yn84UxQNQieDIoP8HG-_7nHJ20D68).

Repository of logos is [here](https://commons.wikimedia.org/wiki/Category:MediaWiki_logo_(2020)) but I guess in our case we'll go for this one https://commons.wikimedia.org/wiki/File:MediaWiki-2020-button.svg

**Comment by kelson42** [comment]
I guess this will automatically happen by next upgrade of mediawiki (docker).

**Comment by kelson42** [comment]
This will happen automatically during the Wikifundi project which require a refresh of repository openzim/mediawiki-docker.

**Comment by kelson42** [comment]
@Popolechien But I have changed OUR logo!
