### ISSUE TITLE
Psiram is still on the page library.kiwix.org

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/web#136]
Previously **Psiram** [was deleted](https://github.com/openzim/mwoffliner/issues/1216).
But it is still present in the [library](http://library.kiwix.org):
![Psiram](https://user-images.githubusercontent.com/65112331/114306342-643ef280-9ae4-11eb-9b1a-a0a9624d899d.gif)

Here are some examples:
- http://library.kiwix.org/psiram_fr_all_maxi_2020-05/M/Counter
- http://library.kiwix.org/psiram_de_all_nopic_2020-04/M/Counter
- http://library.kiwix.org/psiram_en_all_nopic_2020-05/M/Counter

**Comment by kelson42** [comment]
I have deleted all the ZIM files. Library will be updated during the night.
