### ISSUE TITLE
openzim.org is down

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#138]
Started on Friday 14th, shortly before 6 AM UTC

https://www.openzim.org/

**Comment by kelson42** [comment]
i will have a look, but basically fixed this very same problem on wednesday already.

**Comment by kelson42** [comment]
Fixed

**Comment by rgaudin** [comment]
what was the issue ?

**Comment by kelson42** [comment]
We use a DNS `A` entry and this IP has been removed from the reverse-proxy pool by Sloppy. We has the same or a similar problem with wiki.kiwix.org. I fixed the `@` and the `wiki` entry for openzim.org last Wednesday, but forgot about `www`.
