### ISSUE TITLE
"click here" is bad interface design

### ISSUE THREAD

**Issue by VDK** [kiwix/web#142]
There are a lot of places on kiwix.org where visitors are asked to "click here".
This is not in line with the [W3C guidelines on labeling links](https://www.w3.org/QA/Tips/noClickHere)
I would do some copy editing directly but this repository is nothing like what the website looks like atm.

**Comment by VDK** [comment]
On the [download page](https://www.kiwix.org/en/download/) there are several links with the label  "here" or "this link", reference the above W3C guidelines on why that's bad.  Instead of saying the manual is *here* you aught to make *manual* the link. 

It's also confusing to not list options together: the download link for the Play store is mentioned in the paragraph, followed with two alternatives in bullet points. 

I would advice to use the [mobile app store icons](https://365webresources.com/10-mobile-app-download-app-store-google-play-button-templates-for-free-download/) that most users would be familiar with. I might have seen something similar for F-droid in the past.

iTunes has completely rebranded as the App Store. 

I don't see why iOS gets a paragraph when there isn't any download options listed there. 

I don't like the inconsistent behavious of the icons at the top. Their alt labels are also no help. I would expect these to be anker link that would take me to further information  for that category within the same page, instead they're external links. This is unpredictable behaviour. 

Having multiple platforms side by side on the desktop site is needlessly crowded.


Another thing: I noticed [the blog page](https://www.kiwix.org/en/blog/) suddenly has the menu in a serif font.

**Comment by Popolechien** [comment]
@VDK I've taken your comments into account and had a look at what kodi.tv is doing and came up with a revamped/simplified architecture for this [download page](https://www.kiwix.org/en/download/).

I've left the default download buttons at the moment to keep a more conssitent look but am open to discuss. Either way, let me know if you think we've made progress and what else (if anything) could be done before we close this particular ticket.
