### ISSUE TITLE
List Wikivoyage and WikiMed packaged apps on kiwix.org

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/web#143]
@kelson42 @Popolechien You're hopefully aware that I've been regularly publishing packaged apps of [Wikivoyage](https://kiwix.github.io/kiwix-js-windows/wikivoyage-uwp.html) since December 2017, and [WikiMed](https://kiwix.github.io/kiwix-js-windows/wikimed-uwp.html) since January 2018. Since September 2020 I've also been publishing an [Electron version](https://kiwix.github.io/kiwix-js-windows/wikimed-electron.html) of the WikiMed packaged app, which has portable and installable builds for Windows 7/8/10/11, and more recently AppImage and deb packages for Ubuntu, Debian and OpenSUSE (tested on these) for both 64bit and 32bit (and yes, there are users of the 32bit version, both for Windows and Linux).  EDIT: Since November 2021, there is an Electron version of Wikivoyage (English) for Windows and Linux.

~~I have not produced an Electron version of Wikivoyage, because I figure that offline Wikivoyage is something people mostly want on phones, not on laptops or tablets.~~ EDIT: An Electron-based Wikivoyage is now available.

It would be really great if the Wikivoyage and WikiMed apps could be listed on https://www.kiwix.org/en/downloads/kiwix-custom-apps/ and the WikiMed apps also on https://www.kiwix.org/en/wikimed/. Currently the former page says:

> Kiwix Customs Apps combine a specific content package and a reader into one easy to install app. They are available on iOS, Android **and Windows devices**.

However, there is no link to the app for "Windows devices".

If this is possible, then I'd suggest that the best links are these permalinks, as they always point to the latest release:

* https://kiwix.github.io/kiwix-js-windows/wikivoyage-uwp.html  - Wikivoyage UWP (Win10/11)
* https://kiwix.github.io/kiwix-js-windows/wikivoyage-electron.html - Wikivoyage Electron (Win7/8/10/11 + Linux)
* https://kiwix.github.io/kiwix-js-windows/wikimed-uwp.html - WikiMed UWP (Win10/11)
* https://kiwix.github.io/kiwix-js-windows/wikimed-electron.html - WikiMed Electron (Win7/8/10/11 + Linux)

**Comment by Jaifroid** [comment]
Quick note to say that an Electron version of Wikivoyage is now also available. I've edited above post with link. See also https://github.com/kiwix/kiwix-js-windows/issues/211 .

**Comment by Popolechien** [comment]
@Jaifroid Can you please check that https://www.kiwix.org/en/downloads/windows/ is correct before I roll into production?

**Comment by Jaifroid** [comment]
Many thanks for doing this, @Popolechien! It's nearly there, but not quite accurate yet ;-) Just some pesky details... 
Here's what I'd do. These are of course just suggestions (from top to bottom of page):

* Change the title "32-bit compatible (for Windows XP, Vista, etc.)" to:
    + "Light app compatible with any Windows version"
    + If you think it's a good idea to mention the old Windows versions, then I suggest instead: "Light app compatible with any Windows (32bit, XP, Vista, etc.)"
* Remove hyphen in "Kiwix- JS". It should just be a space.
* Please amend the button that says "Windows Store" so that it reads **"Kiwix JS UWP"** and link it to this non-region-specific link (instead of the en-GB version):
    + https://www.microsoft.com/store/apps/9P8SLZ4J979J
* Change button that says "Direct Download" so that it reads **"Kiwix JS Electron"**, and link it to:
    + https://kiwix.github.io/kiwix-js-windows/kiwix-js-electron.html  
* I don't actually offer a WikiMed mini, just the full "app-maxi" version, so please delete text from "Wikimed mini ..." to "... 85% smaller."
* To be consistent, please link the "WikiMed UWP" and "Wikivoyage UWP" buttons directly to the Store versions:
    + WikiMed: https://www.microsoft.com/store/apps/9PHJSNP1CZ8J 
    + Wikivoyage: https://www.microsoft.com/store/apps/9N5SB90Q4JBJ
* Please note the official case for "WikiMed" (middle M is capitalized, including on the buttons);  "Wikivoyage" is correct
* The source code for these versions is on [Kiwix JS Windows](https://github.com/kiwix/kiwix-js-windows/), not Kiwix-JS (which is the repo for the browser extension versions).

Thank you once again! It's exciting to have these officially listed.

**Comment by Jaifroid** [comment]
One extra thought. You could add a section before "Custom apps" that also gives the Web App version:

> ## Installable Progressive Web App (PWA)
> 
> Just visit https://pwa.kiwix.org/ in Chrome, Edge or Firefox for our PWA version. In Chrome and Edge, you can install it directly from within the app, and in Firefox, you can bookmark it. It caches its own code, so it can run offline.

**Comment by Popolechien** [comment]
Ok @Jaifroid I've updated / corrected. I'd rather leave Windows store rather than UWP as the latter is rather obscure for non-developers.

Would it make more sense to mention the Installable Progressive Web App on the [extensions page](https://www.kiwix.org/en/downloads/browser-extensions/)?

**Comment by Jaifroid** [comment]
@Popolechien The PWA can certainly be mentioned on the extensions page instead.

Regarding "Windows Store" that's fine. However, the second button still says "Direct download", instead of "Kiwix JS Electron", and it should link to https://kiwix.github.io/kiwix-js-windows/kiwix-js-electron.html , not to the sideloading UWP package on download.kiwix.org. As it currently stands, there is no link to a version that supports old Windows! (Both buttons lead to a UWP version only compatible with Windows 10/11.) **Only the Electron version is compatible with older Windows.**

Do you want me to provide some brief text to make this clear?

**Comment by Jaifroid** [comment]
Here's what I'd suggest for the text:

> Kiwix JS is a smaller alternative. There is a Windows Store (UWP) version for Windows 10 or 11 tablets, phones, PC and Xbox, and Electron and NWJS versions that are compatible with older Windows. If you want to sideload the Store version, you can get it from [download.kiwix.org](https://download.kiwix.org/release/kiwix-js-windows/kiwix-js-windows.appxbundle), and follow [instructions](https://kiwix.github.io/kiwix-js-windows/kiwix-js-uwp.html).
>
> Button 1: [[Windows Store]](https://www.microsoft.com/store/apps/9P8SLZ4J979J) 
> Button 2: [[Kiwix JS Electron]](https://kiwix.github.io/kiwix-js-windows/kiwix-js-electron.html)

**Comment by Jaifroid** [comment]
Edited text to add "(and Linux)" in parentheses for the Electron version (see edited comment above).

**Comment by Popolechien** [comment]
Done! Thanks a lot.

**Comment by Jaifroid** [comment]
@Popolechien thank you for updating the Windows download page as above.

I've just realized there are two other pages (mentioned also at the top of this issue), that are lacking information about the custom apps for Windows and Linux:

* https://www.kiwix.org/en/downloads/kiwix-custom-apps/
* https://www.kiwix.org/en/wikimed/

Would you be able to add the Windows and Linux WikiMed and Wikivoyage custom apps to the first one, and the WikiMed custom apps to the second? The first of these pages actually mentions that custom apps are available for Windows, but doesn't provide any link to access them.

Keeping things simple, the only links you would need to add for this (under appropriate headings) are:

* [WikiMed for Windows and Linux](https://kiwix.github.io/kiwix-js-windows/wikimed-electron.html)
* [Wikivoyage for Windows and Linux}(https://kiwix.github.io/kiwix-js-windows/wikivoyage-electron.html)

**Comment by Popolechien** [comment]
The first page should have been retired (I'd totally forgotten about it tbh) as I'm trying to weed out duplicates. The other one is a results page for the tests we run with the google adwords which are android/iOS specific.
How did you find them in the first place?

**Comment by Jaifroid** [comment]
@Popolechien These are linked from the footer of every page on kiwix.org (see screenshot below). As a result they also come up in searches for "WikiMed" (on Bing it's the third result, on Google it's much lower down).

![image](https://user-images.githubusercontent.com/4304337/146518272-7b5ef4a8-7c67-41b2-a7d3-7ee70ba6f013.png)

**Comment by Jaifroid** [comment]
Personally I'd suggest keeping these pages (they are well designed) if they are still relevant, even making them more prominent, to aid in discoverability (it's currently quite hard to find content packages from Kiwix.org for the average user, which I know you're working on improving).

Whatever you decide, if these pages are kept, it would be great to add the two links above to the custom apps I make, as users who have managed to find them seem to like them, and I believe these are the only custom apps for Windows and Linux currently.

(I'll be releasing a new English Wikivoyage maxi with the December ZIM over the weekend, and the new WikiMed as soon as the custom app ZIM is released probably early next week. I'm working towards more automation of these releases -- they are currently fully scripted, but there are some technical hurdles to releasing them automatically.)

**Comment by Popolechien** [comment]
I have added the links as requested.

**Comment by Jaifroid** [comment]
Thank you very much!
Happy Solstice!
