### ISSUE TITLE
Design issue on Kiwix Reader download page

### ISSUE THREAD

**Issue by qubist** [kiwix/web#149]
<img width="1440" alt="Screen Shot 2022-03-17 at 9 54 33 PM" src="https://user-images.githubusercontent.com/3607279/158922567-e01589ab-e6a2-44e6-bcc0-220650bb53cb.png">

There should be either more vertical space between or outlines around the icons on this page. It ends up looking like the icons stacked on top of each other are supposed to be related, and is confusing. Here's a mock-up that looks better to me:

<img width="1440" alt="Screen Shot 2022-03-17 at 9 59 53 PM" src="https://user-images.githubusercontent.com/3607279/158923033-70ad2a2b-3025-4c65-82aa-a3e621c4b3a0.png">

**Comment by martin8032** [comment]
I have implemented a new version which should address this issue.

**Comment by kelson42** [comment]
@martin8032 I like it! https://www.kiwix.org/en/download/

**Comment by Popolechien** [comment]
Awesome. Thanks everyone.

**Comment by qubist** [comment]
Amazing! Thank you :) Looks excellent
