### ISSUE TITLE
Add a FLattr button and explain how to give (to Kiwix) on the web site 

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#161]
All in topic...

From https://sourceforge.net/p/kiwix/feature-requests/604/

**Comment by Popolechien** [comment]
Why Wikipedia and not any of the other (free, donation-supported) websites we also offer? I don't think we are supposed to fundraise for others when fundraising for ourselves is already hard enough.

**Comment by kelson42** [comment]
I meant Kiwix, sorry. I have fixed the ticket.

**Comment by Popolechien** [comment]
@kelson42 "_Flattr subscribers install a browser extension that records which websites they frequent and shares this data with Flattr._" 

Are you sure you want this?

**Comment by Popolechien** [comment]
This being said, the ticket reminds me I wanted us to join Open Collective.

**Comment by Popolechien** [comment]
Ok we need to add the following tag to our website's head 

`<meta name="flattr:id" content="7y5rv0">`

I've listed kiwix.org (ping @martin8032), openzim.org (@kelson42) and youzim.it (@rgaudin)

Not clear if/how this works on microsites (e.g. farm.openzim.org or wiki.kiwix.org)

**Comment by rgaudin** [comment]
OK so adding this would only work for flattr users obviously. I can add it to zimfarm and youzim.it but I'm not sure there's an easy way to add it to mediawikis. I couldn't find a flexible enough extension at least.

**Comment by rgaudin** [comment]
Added to zimfarm and youzim.it. Couldn't test as creating a flattr account requires setting up a donation. Also, the website doesn't mentions the extension anywhere and the extension repo is deprecated so I don't know how useful this would be.

**Comment by Popolechien** [comment]
Yeah maybe we've been a little ahead of ourselves here. Their twitter account hasn't been active for 18 months, I don't see any news about them that is less that a few years...

**Comment by martin8032** [comment]
In my perception, Flattr was a thing 10+ years ago. If I read about financial support nowadays, then it's usually via https://www.patreon.com

But I have added the meta tag to www.kiwix.org anyway.

**Comment by Popolechien** [comment]
Spoke to a few folks listed on the website and say it's mostly inactive. Oh well. It is what it is.
