### ISSUE TITLE
Add link to content package page to top-level dropdown menu

### ISSUE THREAD

**Issue by branrickman** [kiwix/web#163]
The current home page (https://www.kiwix.org/en/) only lists reader and wifi hotspot under the top level dropdown: 

![image](https://user-images.githubusercontent.com/61772752/197821939-9deed9d0-690f-462c-b4fc-a8edd493d3b6.png)

In order to find the content packages you have to scroll to the bottom of the page:

![image](https://user-images.githubusercontent.com/61772752/197822158-2b2e5ab9-d8a8-4689-96d4-15cabcf51873.png)

Is there a reason the content packages are so hidden?

**Comment by kelson42** [comment]
Supportive of this! I kind of believed I reported that problem in the past as well.

**Comment by Popolechien** [comment]
Fixed! Thanks for the flag.

![Capture d’écran 2022-10-26 à 09 14 30](https://user-images.githubusercontent.com/21675885/197959340-bcfb8594-6ea9-45dc-8d40-48f8e04941b0.png)
