### ISSUE TITLE
links to our social media

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#164]
* twitter
* linkedin
* facebook
* mastodon

**Comment by Popolechien** [comment]
Facebook is not being actively used, so I'd actually remove it. We also have r/kiwix on Reddit.

This being said, I see we already have facebook and Twitter listed but for the life of me could not find where to access these on the dashboard. But I have a vague recollection that the footer tool only allows for the big ones (TW, FB, and.. G+ ?)

@martin8032 Can you please help/confirm?

To sum up:

- Twitter: already there
- Facebook: remove
- Linkedin: https://www.linkedin.com/company/kiwixoffline
- Mastodon : https://mastodon.social/@kiwix
- Reddit: https://www.reddit.com/r/Kiwix/

**Comment by kelson42** [comment]
I wonder a bit if not maintaining Facebook is a good move. I had in minde this is pretty much used in Africa for example.

**Comment by Popolechien** [comment]
And South America and the Arab world as well. We simply don't have the time/ressources/material to publish something for that platform, and it's not like there'd be a visible gain from that (the ad campaign we ran 2 years ago was very meh in terms of impact). 

Facebook is also very language-specific so we'd have to maintain pages in French, Arabic and Spanish. I'm not going down that path. At this stage the only thing we can afford are places where content writes itself (reddit, twitter) or where we can hope to hook partnerships (Linkedin).

**Comment by martin8032** [comment]
Currently the social icons are set in the Divi theme options, which allows only Facebook, Instagram, Twitter and RSS.

But there are of course other ways to solve this. In the end of the day it's just a linked icon.

**Comment by kelson42** [comment]
AFAIK this has been fixed in latest version of the web site
