### ISSUE TITLE
Setup Analytics 4

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#165]
Google has announced they are sunsetting Google analytics and moving to analytics 4.

I know there's some discussion as to whether we actually _want_ to be using Google's tools, but as long as an acceptable alternative has not been put forward then we'll have to work with that.

**Comment by kelson42** [comment]
We have stats.kiwix.org and we don't use anymore Google analytics since a while. What is the problem with current setup? We should not open ticket about solutions but about problems.

**Comment by Popolechien** [comment]
Ok I'd forgotten we'd gotten rid of Analytics. My bad.
