### ISSUE TITLE
Revamp iOS & macOS web pages

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#166]
Talking about:
* https://www.kiwix.org/en/downloads/ios/
* https://www.kiwix.org/en/downloads/macos/

MacOS pages provides links to old version

iOS page says minimal version is iOS11 but it is now iOS14. Maybe we should better say nothing about that there. Information is anyway given automatically on app store.

Considering that this is the same app now, we coyld consider to merge both pages in one.

**Comment by Popolechien** [comment]
Done.

**Comment by kelson42** [comment]
Can you please:
* Rename the page in `apple` in place `ios`
* Secure we don't create broken links by redirecting https://www.kiwix.org/en/downloads/macos/ and https://www.kiwix.org/en/downloads/ios/ to https://www.kiwix.org/en/downloads/apple/
* Change links pointing to https://www.kiwix.org/en/downloads/ios to https://www.kiwix.org/en/downloads/apple/
* Ensure translated versions work fine, https://www.kiwix.org/fr/download/ is wrong for example

**Comment by Popolechien** [comment]
Send jobs to all translators (Arabic has issues with WPML, not sure anything works there atm). French and German are already up-to-date.

**Comment by kelson42** [comment]
Sorry, but only part of the job has been done, old pages are transformed in redirects and we should keep the dmg button.
