### ISSUE TITLE
www.kiwix.org download page is not reactive/mobule friendly

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#169]
![Screenshot_20230114-101713](https://user-images.githubusercontent.com/1029718/212465081-d3fb4715-cadf-4ac9-8cc0-7111656ff3a2.png)

**Comment by martin8032** [comment]
Fixed. Please test.

**Comment by kelson42** [comment]
@martin8032 Thank you! It works again (I kind of assume this is a regression which has been introduced at some point) perfectly looks like.
