### ISSUE TITLE
Put a link to kiwix-html5 on homepage

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#17]
I think that would make sense:
* if firefox -> a link to firefox extension (in the app store)
* if chrome -> a link to chrome extension (in the app store)

**Comment by Popolechien** [comment]
done.

**Comment by kelson42** [comment]
@Popolechien Cool, thx
@mossroy This is for you http://www.kiwix.org/fr/

**Comment by mossroy** [comment]
Great, thanks!

**Comment by mossroy** [comment]
Maybe it would be worth mentioning on the website that the browser extensions are slower and do not have all features.

**Comment by Popolechien** [comment]
Nah. You can eventually do it in the extensions description page, but otherwise the site is mostly meant to showcase what we have.
