### ISSUE TITLE
Update IP database on matomo

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#170]
Don't know if that's the correct phrasing but our 7th-most visited country in 2022 (and 1st region and 1st city) is "Unknown". I suspect there is a database of IP addresses that needs updating.
![Capture d’écran 2023-01-24 à 14 54 02](https://user-images.githubusercontent.com/21675885/214313062-6eb5cedd-e75d-4766-8a0d-3db02cc20e28.png)

**Comment by rgaudin** [comment]
We are using DB-IP Lite database, the one that's free. It's up-to-date so I don't think there's anything we can do about it.
We could test maxmind's one (they also have a lite, free version– but how would we accurately test????) or we could pay a subscription to have access to the *full* DB…

TBH, I have no idea what kind of numbers would be legitimate for both *as-accurate-as-possible* and *using-free-db* scenarios.

Looking at download.kiwix.org over the last 3 years, we have `1.9%` of visitors marked *Unknown*.

**Comment by kelson42** [comment]
I don't see either what could be done to have less unknown. Closing.
