### ISSUE TITLE
Mission - English - Annual report - text is not clearly visible

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#173]
Description:

On "Annual Report" page, the text on banner image is not clearly visible.

Device, OS and Browser Details:
All

Steps To Reproduce:
- Visit the site URL.
- Hover on Mission from the header menu.
- Hover on the Annual Report.
- Click on Annual Report.
- Observe the text present on the banner image in the annual report page.
- Observe the expected result.

Expected Result:
Text should be clearly visible on the banner image of the annual report page.

Actual Result:
In the banner image of the annual report, the text is not clearly visible on image.

![216586996-9f19ad12-5364-45e7-80da-dc79c56aadf5](https://user-images.githubusercontent.com/98155966/217826062-7b15cc2d-437e-456d-b949-1c22d31f8fbb.png)

**Comment by Popolechien** [comment]
We are going to publish out 2022 report so might not be worth working on this.
