### ISSUE TITLE
Homepage - Arabic - respective page is not open

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#174]
Description:
For Arabic language, While clicking on the header sub menu, the respective page is not open.(Except 2nd submenu - 1st header menu & except content from 2nd header menu)

Device, OS and Browser Details:
All

Steps To Reproduce:
- Visit the site URL.
- Observe the top header.
- Click on arabic language.
- Hover on header menu one by one.
- Click on sub header menu one by one.
- Observe the expected result.

Expected Result:
After selecting of sub header menu, the user should redirect to the respective page.

Actual Result:
While clicking on the header sub-menu, the respected page is not open. It goes to the footer bar.

Screenshot/Video:
https://user-images.githubusercontent.com/98155966/217827768-400637d9-e606-4841-9b97-3cbbff3b440f.mp4

**Comment by Popolechien** [comment]
This would be the `Support us` page

**Comment by Popolechien** [comment]
@martin8032 I've assigned the translation but in the meantime should this link / page at least redirect to the English support page by default?

**Comment by martin8032** [comment]
I'm not sure if a real redirect is the best solution, since it might affect the translator as well.

I would instead suggest adding a custom link to the AR menu, pointing to the EN version of the «Support Us» page. But for that, the AR menu must be created first.

**Comment by kelson42** [comment]
@Popolechien We need translations to be done pretty quickly otherwise this will be a eternal mess. I see no excuse for languages for which we have native speakers within the team… or do I miss a point?

**Comment by martin8032** [comment]
As far as I can see, the page https://www.kiwix.org/ar/%d8%a7%d8%af%d8%b9%d9%85%d9%86%d8%a7-2/ was simply not 100% translated and therefore empty. I have added the missing (1) translation and published the page.
