### ISSUE TITLE
Homepage - Arabic, German, French- - content is not translated into respective language

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#176]
Description:
For Arabic, German, French language, content on banner image and footer content are not translated into the respective language.

Device, OS and Browser Details:
All

Steps To Reproduce:
- Visit the site URL.
- Observe the top header.
- Select arabic language.
- Observe the banner image content.
- Scroll down to footer section.
- Observe the footer content.
- Observe the expected result.

Expected Result:
After selecting the arabic language, all content should be display in arabic language.

Actual Result:
Banner image content and footer content is not translated in arabic language.

Screenshot:
![216582413-36230a6c-1942-4614-ac70-92c358b2bad1](https://user-images.githubusercontent.com/98155966/217829694-7c56ea11-33ba-4e93-914f-0ae57f8b16c0.png)

**Comment by Popolechien** [comment]
Translation is ongoing @ravanjaltaie
