### ISSUE TITLE
Homepage - English, Français, Deutsch, Русский, Español - Mission - Space between heading and sub heading is extra

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#178]
Description:
In "What is kiwix" submenu from Mission header menu, the space between heading and sub heading is extra.

Device, OS and Browser Details:
All

Steps To Reproduce:
- Visit the site URL.
- Hover on Mission from the header menu.
- Hover on What is kiwix?.
- Click on What is kiwix?.
- Observe the expected result.

Expected Result:
The space between "What is Kiwix?" and "The short story" should be proper.

Actual Result:
Space between the heading and sub heading is extra.

Screenshot:
![216585455-22712793-7f35-4cee-9692-806ed367b4f2](https://user-images.githubusercontent.com/98155966/217831179-b2bbabef-31df-486f-b8eb-68e4f562b66e.png)

**Comment by Popolechien** [comment]
Looks like it's a feature from how the page is built. Having text in two separate rows adds the extra space.

![Capture d’écran 2023-02-09 à 15 39 35](https://user-images.githubusercontent.com/21675885/217843812-cf75edd8-0cab-4e3f-b016-33afcfdbf9be.png)
