### ISSUE TITLE
Homepage - Arabic, Русский - header menu - "Content" submenu is not translated in arabic language

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#179]
Description:
For Arabic and Russian language, the "Content" submenu is not translated into the respective language.

Device, OS and Browser Details:
All

Steps To Reproduce:
- Visit the site URL.
- Observe the top header.
- Select Arabic language.
- Hover on the middle header menu.
- Observe the sub-menu.
- Observe the expected result.

Expected Result:
"Content" sub-menu should be display in arabic language.

Actual Result:
"Content" submenu is not translated in arabic language.

Screenshot:
![216582099-c0b440f7-5f36-4595-a2c8-77e839133d2d](https://user-images.githubusercontent.com/98155966/217831692-ce6b9f07-4e60-4334-9542-7df286fcb5ec.png)

**Comment by Popolechien** [comment]
@martin8032 Same as #181 - can't find where the string can be assigned.

**Comment by martin8032** [comment]
See my comment at #181
