### ISSUE TITLE
Homepage - Russian - Middle header menu - "Kiwix reader" is not translated in Russian language

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#181]
Description:
For Russian language, from middle header menu "Kiwix reader" is not translated into the respective language.

Device, OS and Browser Details:
All

Steps To Reproduce:
- Visit the site URL.
- Observe the top header.
- Select the Russian language.
- Observe the middle header menu.
- Observe the expected result.

Expected Result:
"Kiwix reader" should be display in the Russian language.

Actual Result:
"Kiwix reader" is not displayed in the Russian language.

Screenshot:
![216581538-c9c7c744-cc85-4111-a7d7-b23a268da997](https://user-images.githubusercontent.com/98155966/217832806-8f3269cc-b8bd-4992-9c20-1e854e907a2f.png)

**Comment by Popolechien** [comment]
@martin8032 Can't find where the string is located, `Navigation menu` is empty

![Capture d’écran 2023-02-09 à 15 21 33](https://user-images.githubusercontent.com/21675885/217838617-d9de1d9c-780b-4519-91bb-e102a9b94ab3.png)

**Comment by martin8032** [comment]
I don't fully understand how this was done, but menus should be translated under **Appearance > Menus** (see the German and the French versions).

**Comment by Popolechien** [comment]
@martin8032 Yes I am a little lost too - I searched for the string and specifically translated it, but to no avail. Then looking into `WPML` > `WP Menu Sync` I see that for every language content if flagged differently as `content @ar`, `content @fr`, etc.

![Capture d’écran 2023-02-10 à 12 35 40](https://user-images.githubusercontent.com/21675885/218083262-2fd96234-4673-4b33-8ac7-ad1abd4f5cb5.png)

**Comment by martin8032** [comment]
The menu sync feature is not 100% reliable according to my experience. Since we have only a small website, building the menu in each language manually would be my preferred method.

**Comment by kelson42** [comment]
@martin8032 Do we have an upstream bug or similar?

**Comment by martin8032** [comment]
I'm afraid I don't understand your question.

**Comment by kelson42** [comment]
@martin8032 Sorry for jargonizing. I meant that if something (not sure if this is Wordpress, or a Wordpress plugin) is not reliable then it might be a bug. It's important to report bug wherever they belong (upstream).

**Comment by martin8032** [comment]
The menu sync feature is part of the WPML plugin. I had issues with it on several websites, but I can't tell for sure that it is a bug. And I don't have the time to investigate this in detail. As long as our translations are way behind, managing the menus manually for each language is the better method anyway.
