### ISSUE TITLE
Homepage - Français, Deutsch, Русский - some logo missing

### ISSUE THREAD

**Issue by ghost** [kiwix/web#182]
Description:
On the homepage in the middle section, for Français, Deutsch, Русский languages some logo are missing.

Device, OS and Browser Details:
All

Steps To Reproduce:
- Visit the site URL.
- Scroll down to the middle section of the page.
- Observe the logo.
- Observe the expected result.

Expected Result:
Logo "Scaleway open source program", "ENDLESS", "ORY", and "gandi.net" should be present on the homepage for Français, Deutsch, Русский languages.

Actual Result:
Logo "Scaleway open source program", "ENDLESS", "ORY", and "gandi.net" are not present on the homepage for Français, Deutsch, Русский languages.

Screenshot:
![216581310-09506f76-979e-4b69-b834-bddb3581293e](https://user-images.githubusercontent.com/98155966/217833313-86c3158c-5816-4eae-bcc8-f9dd7d0df530.png)

**Comment by Popolechien** [comment]
@martin8032 This not being actual text, how come this is not automatically ported to other languages when we edit the source (English) version?

**Comment by martin8032** [comment]
That's how it works. Just send a page through the translation editor to update images in the other language.

Example: https://www.kiwix.org/de/ has now the current logos.

**Comment by kelson42** [comment]
@martin8032 @Popolechien Do I understand properly: even if a part of a page with nothing to translate is modified (in English) then the page has to be validate again in each language again?

**Comment by Popolechien** [comment]
@kelson42 Correct.

**Comment by kelson42** [comment]
@Popolechien This is a heavy weakness in the translation module then... I'm disapointed to discover every three tikets that actually we face a limitation of the software. At some point, we probably then will have to reconsider the software infrastructure.

**Comment by martin8032** [comment]
When you only exchange an image in the EN version and safe the page, then the DE version is updated instantly. But as soon as there is text involved (and image ALT texts are also text), then you are required to update the translations as well – which makes perfectly sense.

**Comment by kelson42** [comment]
> When you only exchange an image in the EN version and safe the page, then the DE version is updated instantly. But as soon as there is text involved (and image ALT texts are also text), then you are required to update the translations as well – which makes perfectly sense.

As far as I understand here there is nothing to translate, so it does not make sense. The i18n framework should allow the user to decide what is the template, and what is the content (to be translated).

**Comment by martin8032** [comment]
We are talking about the logos on the homepage, right? These logos belong to the regular content of that page. Logos are images. Images have ALT texts. Therefore, a translation is required if you add new logos in the EN version of the homepage.

**Comment by kelson42** [comment]
Not all ALT texts should be translated obviously. This is the flaw in this implicit behaviour.
