### ISSUE TITLE
Homepage - German - text is not translated

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#183]
Description:
On the homepage, "Internet offline" is not translated into german language when selecting the German language.

Device, OS and Browser Details:
All

Steps To Reproduce:
- Visit the site URL.
- Observe the top header.
- Select the German language.
- Observe the "Internet offline" text on the banner image.
- Observe the expected result.

Expected Result:
On selection of German language, the text should be translated into german language.

Actual Result:
On the homepage, "Internet offline" is not translated into german language when selecting the German language.

Screenshot:
![216596250-1ea05a9a-0108-4929-a95d-d29cd8ce87b3](https://user-images.githubusercontent.com/98155966/217833953-54a5cb03-6cc7-4d4d-894a-0e966106f806.png)

**Comment by Popolechien** [comment]
Yeah that would sound weird if _offline_ had to be translated to `nicht angeschlossen`. Internet offline is "proper" (quote marks) German.
