### ISSUE TITLE
SEO Fixes - Add H1 tags where missing

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#185]
List of h1 missing tags: https://docs.google.com/spreadsheets/d/1Q5yBDMZIAMXndKvE8YjHFAg0PqXpj2wNBrTv5MIDx24/edit#gid=713033994

Description:
There are some pages on the site which do not have an H1 tag in place. H1 tags are a direct factor for Google's ranking algorithm. Pages which have a missing, the content is empty or has a whitespace. The should describe the main title and purpose of the page.

Resolution:
- Ensure important pages have concise, descriptive and unique headings to help users, and enable search engines to score and rank the page for relevant search queries. 
- To add these tags to the initial text document with information for future site pages.
- If there is a problem with the code, find the respective field and add this special

**Comment by Popolechien** [comment]
@martin8032 These pages (blog & categories) seem to be dynamically generated. Not sure this is something we can fix.

Thoughts?

**Comment by martin8032** [comment]
Let's take this one as an example: https://www.kiwix.org/en/category/android/

This is what's called an archive in WordPress terms, and it's defined by a template, so you could add an H1 to the template.

**Comment by Popolechien** [comment]
Ok thanks. Note sure these fall under "Important pages" SEO wise, meaning that adapting the templates might not be worth the effort.

I'll close the ticket, but feel free to re-open if you think it's important.
