### ISSUE TITLE
SEO Fixes - Reduce H1 tags character length

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#187]
List of URLs with charater length more than 70 - https://docs.google.com/spreadsheets/d/1kFujmEV0Q9bVVFOzd_sqLJrDjaIjCKkr13S_Fxca9h4/edit#gid=1993406052

Description:
The h1 plays the role of the headline of the page or article. Headings are formatted using visual styles that convey their relative importance – h1 typically has the greatest font size. An overly long h1 tag may lower the power of the text embedded in this tag.
Pages which haves over the configured length. There is no hard limit for characters in an, however they should be clear and concise for users and long headings might be less helpful.  Ideally Character length should be 20-70 characters.

Resolution:
- Write concises for users, including target keywords where natural for users - without keyword stuffing.
- Edit h1 tags so that they have 20-70 characters in length, as recommended.

**Comment by Popolechien** [comment]
Reduced to 50 characters.
