### ISSUE TITLE
Homepage - Hotspot - French - Extra space

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#194]
Description:
In the "Hotspot" header menu, Extra space between the heading and subheading.

Device, OS and Browser Details:
All

Priority
Medium

Steps To Reproduce:
- Visit the site URL.
- Observe the top header bar.
- Select the French language.
- Click on the Hopspot header menu.
- Observe the heading and subheading below the header menu.
- Observe the expected result.

Expected Result:
Space between "Hotspot Kiwix" and "Qu’est-ce qu’un hotspot?" should be proper.

Actual Result:
Space between "Hotspot Kiwix" and "Qu’est-ce qu’un hotspot?" is not proper.

Screenshot:
![216610257-2e6b8cca-41ec-4cf4-b734-91bfd8d1544b](https://user-images.githubusercontent.com/98155966/218093979-c6af3de5-4b97-4a6a-8310-10e3e55433c7.png)

**Comment by Popolechien** [comment]
Fixed.

**Comment by martin8032** [comment]
Just a remark: We have the Divi page builder in place on this website. You can adjust spacings easily through the page builder options and don't have to deal with CSS code.
