### ISSUE TITLE
SEO Fixes - Invalid HTML Elements in Head

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#196]
Link for the URLs - https://docs.google.com/spreadsheets/d/1QMRqKQzq04iRxqz39hkb2dwbz1TilqHH2bO1bxoN8-c/edit#gid=2126697808

Priority
High

Description
These are the Pages with invalid HTML elements within the header<head>.  When an invalid element is used in the <head>, Google assumes the end of the <head> element and ignores any elements that appear after the invalid element. This means critical <head> elements that appear after the invalid element will not be seen. The <head> element as per the HTML standard is reserved for title, meta, link, script, style, base, noscript and template elements only.

Resolution
- You will first need to establish what the <noscript> is and what it is doing. It may be possible to simply move the <noscript> out of the <head>, and into the <body>, where such elements are valid. All invalid elements should be removed from the <noscript>, if it is to remain in the <head>.
- Ensure the <head> element only uses valid elements as per HTML specifications to ensure critical tags are seen by search engines.
- Common invalid elements include <img> and <iframe> elements. Google strongly recommend against including them in the <head>, but if you must, place these invalid elements after the ones you want Google to see.

**Comment by Popolechien** [comment]
> `You will first need to establish what the is and what it is doing. It may be possible to simply move the out of the , and into the `

@svikrantaxioned I think you a couple of words.

**Comment by svikrantaxioned** [comment]
Hi @Popolechien
Can you please elaborate the above comment

**Comment by Popolechien** [comment]
@svikrantaxioned What does `It may be possible to simply move the out of the , and into the` mean? (first bulletpoint in your initial comment)

Ah got it, it's markup that github does not display. Correct text is

Description
These are the Pages with invalid HTML elements within the header `<head>`.  When an invalid element is used in the `<head>`, Google assumes the end of the <head> element and ignores any elements that appear after the invalid element. This means critical `<head>` elements that appear after the invalid element will not be seen. The `<head>` element as per the HTML standard is reserved for title, meta, link, script, style, base, noscript and template elements only.

Resolution
- You will first need to establish what the `<noscript>` is and what it is doing. It may be possible to simply move the `<noscript>` out of the `<head>`, and into the `<body>`, where such elements are valid. All invalid elements should be removed from the `<noscript>`, if it is to remain in the `<head>`.
- Ensure the `<head>` element only uses valid elements as per HTML specifications to ensure critical tags are seen by search engines.
- Common invalid elements include `<img>` and `<iframe>` elements. Google strongly recommend against including them in the `<head>`, but if you must, place these invalid elements after the ones you want Google to see.

Don't forget to put such code between apostrophes ( ` )

**Comment by svikrantaxioned** [comment]
ok. Understood

**Comment by Popolechien** [comment]
@svikrantaxioned Ah sorry but the link points to a file that has been deleted?
