### ISSUE TITLE
Homepage - English, Русский - hyperlink is not added

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#199]
Description:
In Russian language, in "Доступ к карточному магазину" page, hyperlink is not added for "http://yourname.hotspot/", "http://goto.kiwix.hotspot/", "http://network_name.hotspot".

Severity:
Major

Priority:
High

Device, OS and Browser Details:
All

Steps To Reproduce:
- Visit the site URL.
- Observe the top header bar.
- Click on Русский.
- Hover on Скачать Kiwix Reader.
- Click on Доступ к карточному магазину.
- Scroll down to Использование точки доступа & Как использовать изображение, которое я только что загрузил? section one by one.
- Observe "http://yourname.hotspot/" & "«[http://goto.kiwix.hotspot»](http://goto.kiwix.xn--hotspot-yna/) (или http://network_name.hotspot)".
- Observe the expected result.

Expected Result:
For given "http://yourname.hotspot/" & "[http://goto.kiwix.hotspot","http://network_name.hotspot](http://goto.kiwix.hotspot%22%2C%22http//network_name.hotspot)" text should be hyperlinked.

Actual Result:
In "Доступ к карточному магазину" page, hyperlink is not added for "http://yourname.hotspot/", "[http://goto.kiwix.hotspot","http://network_name.hotspot](http://goto.kiwix.hotspot%22%2C%22http//network_name.hotspot)".

Screenshot:
[218088800-98c5d523-07e6-4970-9c91-bc8a5d347a95.webm](https://user-images.githubusercontent.com/98155966/219367736-2f3daa11-ab69-446d-b4fb-9c1e474381f5.webm)

**Comment by kelson42** [comment]
@Popolechien Any reason to not fix this?

**Comment by Popolechien** [comment]
@kelson42 Yes, this is on purpose. As these links do not point to actual websites Wordpress' link checker will flag them as faulty/problematic.

**Comment by kelson42** [comment]
@Popolechien Then why creating hyperlink? Or create an hypelink which is a local page loop?

**Comment by Popolechien** [comment]
@kelson42 Look at the page and if you still have any question ping me directly on slack. There is no issue to solve here.
