### ISSUE TITLE
Update geolocalisation database in statistics tool

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#20]
The stats tool at http://stats.kiwix.org/ does not give useful information when it comes to countries of origin for visitors to kiwix.org and others.
![capture d ecran 2017-06-27 a 14 49 43](https://user-images.githubusercontent.com/21675885/27588345-258ccf2e-5b48-11e7-8a12-ffee789aafb7.png)

**Comment by kelson42** [comment]
Unfortunately, I can not reproduce the pb, I do not have so much of "unknown" countries.

**Comment by Popolechien** [comment]
Try that link - and expand the number of countries in the right hand side window: http://stats.kiwix.org/index.php?module=CoreHome&action=index&idSite=5&period=day&date=yesterday#?idSite=5&period=year&date=2017-07-06&category=General_Visitors&subcategory=UserCountry_SubmenuLocations
But now that the db haas been updated it is not so much of an issue anymore. I'm therefore closing the ticket.

**Comment by Popolechien** [comment]
oups I gave you the wrong link: http://stats.kiwix.org/index.php?module=CoreHome&action=index&idSite=2&period=day&date=yesterday&updated=1#?idSite=2&period=year&date=2017-07-06&category=General_Visitors&subcategory=UserCountry_SubmenuLocations

**Comment by kelson42** [comment]
fixed
