### ISSUE TITLE
Performance Audit and Fixes

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#201]
Link to URL's Score and Opportunities - https://docs.google.com/spreadsheets/d/1CB3wwaOO4DVGXD0Wl-KKO8y7s-8y8hWpgObIK1kg4FA/edit#gid=0

Link for Audit Report for URL's of Different Pages - https://drive.google.com/drive/u/0/folders/16elerDgfBuVlcH5BfOjiHvckP5WWUXI1

Priority 
Medium

Description
- Performance Audit result shows that Mobile score are not good and needs improvement
- All the opportunities to be worked upon on the page are been listed in the Scores and Opportunity Sheet
- Core web Vitals Assessment for Mobile Failed. Needs improvement in FCP, LCP and CLS scores.

**Comment by kelson42** [comment]
@svikrantaxioned Thank you but the second link is not public.
