### ISSUE TITLE
SEO Fixes - Security: HTTP URLs

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#203]
Link for the URLs - https://docs.google.com/spreadsheets/d/1RO-UM3rP92ws5-_w6gL3ab4ul2fHsa0zfyHt5z3gXs8/edit#gid=327183677

Priority
High

Description
HTTP URLs that are encountered in the crawl. All websites should be secure over HTTPS today on the web. Not only is it important for security, but it's now expected by users. Chrome and other browsers display a 'Not Secure' message against any URLs that are HTTP, or have mixed content issues (where they load insecure resources on them). To view how these URLs were discovered, view their 'inlinks' in the lower window tab. You can also export any pages that link to HTTP URLs via 'Bulk Export > Security > HTTP URLs Inlinks'.

Resolution
All URLs should be to secure HTTPS pages. Pages should be served over HTTPS, any internal links should be updated to HTTPS versions and HTTP URLs should 301 redirect to HTTPS versions. HTTP URLs identified in this filter that are redirecting to HTTPS versions already should be updated to link to the correct HTTPS versions directly.

**Comment by kelson42** [comment]
@svikrantaxioned Thank you for your proposal. I agree on the principle but It is missing an information: on which page(s) are these HTTP URLs?

**Comment by Popolechien** [comment]
@kelson42 Look at the google doc link?

**Comment by kelson42** [comment]
@Popolechien I don't get it, this sheet should have at least two colums:
* a column with the url where we have the problem
* the wring http url itself.

Where are, or what is the name of these two columns.... i see only one column we url?!

**Comment by martin8032** [comment]
1. When I click these URLs, I am redirected to an HTTPS connection, so I don't see a real issue here.
2. To fix them, I need to know on which pages these links are published.
