### ISSUE TITLE
SEO Fixes - Page Titles: Below 30 Characters

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#205]
Link for the URLs - https://docs.google.com/spreadsheets/d/1o2wSsrE-mCUb3W-CvsMY6owq7WTnNOlSh7RXRpT7WqA/edit#gid=915664444

Priority
Medium

Description
Pages which have page titles under the configured limit. This isn't necessarily an issue, but it does indicate there might be room to target additional keywords or communicate your USPs.

Resolution
Consider updating the page title to take advantage of the space left to include additional target keywords or USPs.

**Comment by Popolechien** [comment]
Fixed where it made sense.
