### ISSUE TITLE
SEO Fixes - Page Titles: Below 200 Pixels

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#206]
Link for the URLs - https://docs.google.com/spreadsheets/d/1kRhtvdQNAhtPTRITi1mpGoek7mumrBh_o_hGl__e0P0/edit#gid=1249548237

Priority
Medium

Description
Pages which have page titles much shorter than Google's estimated pixel length limit. This isn't necessarily an issue, but it does indicate there might be room to target additional keywords or communicate your USPs.

Resolution
Consider updating the page title to take advantage of the space left to include additional target keywords or USPs.

**Comment by Popolechien** [comment]
Fixed where it made sense.
