### ISSUE TITLE
SEO Fixes - Page Titles: Over 60 Characters

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#208]
Link for the URLs - https://docs.google.com/spreadsheets/d/1z2ZzbMQB94AkG4DjRJAWXfSTxnUYJumoa_2_1SNl5r4/edit#gid=2095846199

Priority
Medium

Description
Pages which have page titles that exceed the configured limit. Characters over this limit might be truncated in Google's search results and carry less weight in scoring.

Resolution
Write concise page titles to ensure important words are not truncated in the search results, not visible to users and potentially weighted less in scoring.

**Comment by Popolechien** [comment]
Done.
