### ISSUE TITLE
SEO Fixes - Page Titles: Duplicate

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#209]
Link for the URLs - https://docs.google.com/spreadsheets/d/1RPZrTse6RAfADaRwEy6Ew00ZE-peugj7wyVnl8LA_MM/edit#gid=242619900

Priority
Medium

Description
Pages which have duplicate page titles. It's really important to have distinct and unique page titles for every page. If every page has the same page title, then it can make it more challenging for users and the search engines to understand one page from another.

Resolution
Update duplicate page titles as necessary, so each page contains a unique and descriptive title for users and search engines. If these are duplicate pages, then fix the duplicated pages by linking to a single version, and redirect or use canonicals where appropriate.

**Comment by Popolechien** [comment]
Fixed on the website - wiki will be deprecated so no need to run a fix.

**Comment by rgaudin** [comment]
How so ?
