### ISSUE TITLE
F-Droid icon/link

### ISSUE THREAD

**Issue by AnBuKu** [kiwix/web#21]
As "Kiwix Offline Wikipedia reader" is available on F-Droid website

https://f-droid.org/repository/browse/?fdid=org.kiwix.kiwixmobile

It might make sense to add a F-Droid icon and text, as for iOS or Android, to:

- http://www.kiwix.org -> DOWNLOADS For computers or smartphones
- http://www.kiwix.org/downloads/ -> Kiwix software Get the software now, pick your content later

**Comment by Popolechien** [comment]
Updated the downloads page for every language (front page is more for a general audience).
