### ISSUE TITLE
www.kiwix.org Design Revamp - Homepage

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#211]
Description - 
Axioned presented two versions of the homepage design: Version 1 and Version 2. Version 2 is approved with minor adjustments

Simple Version with less imagery
[Kiwix Homepage Version 1 (Desktop)](https://www.figma.com/proto/atKBgNfsDz5MvmsOGHY2ls/kiwix?page-id=0%3A1&node-id=49%3A39&viewport=46%2C303%2C0.06&scaling=min-zoom)

Modern Version with more imagery
[Kiwix Homepage Version 2 (Desktop)](https://www.figma.com/proto/atKBgNfsDz5MvmsOGHY2ls/kiwix?page-id=0%3A1&node-id=53%3A174&viewport=-2154%2C1337%2C0.5&scaling=scale-down-width)
[Kiwix Homepage Version 2 (Mobile)](https://www.figma.com/proto/atKBgNfsDz5MvmsOGHY2ls/kiwix?page-id=0%3A1&node-id=63%3A49&viewport=46%2C303%2C0.06&scaling=min-zoom)

Meta Data Description - 
Title: Kiwix - Free and open-source software that brings knowledge to millions
Description: Kiwix is a free and open-source software that allows you to access knowledge offline without internet connection. Download Kiwix Desktop or Kiwix for Mobile today.
Keywords: kiwix, offline wikipedia, open-source, knowledge, software

**Comment by rgaudin** [comment]
First link not working

**Comment by svikrantaxioned** [comment]
Hi @rgaudin 
Please Ignore Version 1 link as Version 2 was approved

**Comment by sumeetuprdxn** [comment]
Hi @rgaudin: 

Sorry for delay here. 

Here is the Figma URL: https://www.figma.com/file/atKBgNfsDz5MvmsOGHY2ls/kiwix?node-id=126-244&t=E2Opi57AQX4IqwRa-0. You should be referring to "For Developers" tab from the left hand navigation.

Meta Data Description to be considered during the building of page as below _(this is only a recommendation, but if you have any alternative data then feel free to use them.)_

- **Title:** Kiwix - Free and open-source software that brings knowledge to millions
- **Description:** Kiwix is a free and open-source software that allows you to access knowledge offline without internet connection. Download Kiwix Desktop or Kiwix for Mobile today.
- **Keywords:** kiwix, offline wikipedia, open-source, knowledge, software

Regards,
Sumeet

**Comment by svikrantaxioned** [comment]
Hi All,

Moving this ticket to separate repo i.e. [libkiwix](https://github.com/kiwix/libkiwix)

**Comment by rgaudin** [comment]
libkiwix only hosts the WebUI you can see at https://library.kiwix.org/ ; not the www.kiwix.org one

**Comment by svikrantaxioned** [comment]
@rgaudin ok Understood we will keep this ticket intact on this repo. I will delete the issue posted on libkiwix

**Comment by Popolechien** [comment]
Since we're moving to a more direct approach I believe we can close this ticket, can't we?
