### ISSUE TITLE
www.kiwix.org Design Revamp - "Get Involved" page

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/web#212]
Description
Here is the Figma URL: https://www.figma.com/file/atKBgNfsDz5MvmsOGHY2ls/kiwix?node-id=126-244&t=E2Opi57AQX4IqwRa-0. You should be referring to "For Developers" tab from the left hand navigation.

Here are some development guidelines to keep in mind:
- The "Get Involved" menu navigation will contain 3 submenus: Donate, Volunteer, and Partner with us.
- Each submenu should lead the user to the corresponding section of the page, which can be shared via social media.
- The section titles (e.g. "Donate", "Volunteer", "Partner with us") should be H2 tags.
- The page title should be formatted as an H1 tag.
- Clicking on the "Volunteer" section will open a new tab with a Github link and instructions for the user.
- Clicking on "Contact Us" will take the user to the contact form.

Meta-data for the page:
- Title: Get Involved - Join the Kiwix Community
- Description: Join the Kiwix community by donating, volunteering, or contributing to our open-source software development.
- Keywords: get involved, kiwix community, donate, volunteer, contribute

If you have any questions or need more information, please don't hesitate to reach out.

**Comment by kelson42** [comment]
@svikrantaxioned Thank you very much for this new design proposal.

**Comment by Popolechien** [comment]
@kelson42 Yes, #211 relates to the homepage and this present issue is for a different page (_get involved_) that will funnel potential donors, volunteers and partners.

**Comment by Popolechien** [comment]
Hi @svikrantaxioned 

**In the "Volunteer" section** 
I would change the Test and Report bugs to Report bugs, which opens another issue: there is not one single bug reporting funnel, but at least three (and therefore three buttons?) to github.com/kiwix/apple, /kiwix-android, and /kiwix-desktop 
It seems to me that there would be a design impact there.

We are not really entertaining a community (third Volunteer box) but we encourage people to contribute code (via the /code page).

All three CTAs should be bottom aligned (currently they're not as the text has different length).

Also to be clear and based on the front page design all three sections (donate, volunteer, partner) will have anchor links, correct?

Rest is ok.
