### ISSUE TITLE
Web redirection not updated

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#218]
Following roll out of our new website I've updated support.kiwix.org to point at https://kiwix.org/en/get-involved/#donate but the redirect keeps leading users to kiwix.org/support (and a 404 page).
![Capture d’écran 2023-08-22 à 11 59 58](https://github.com/kiwix/web/assets/21675885/403b31aa-7b5c-4ecd-bc16-41c58aabad25)

Update was made more than 24 hours ago.

**Comment by kelson42** [comment]
@Popolechien https://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s. This is probably what happens here, without purging your cache, there is no way to solve this PR IMO.
