### ISSUE TITLE
Change tile for WikiMed (Electron) custom app

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/web#220]
@Popolechien Here is the permalink for the WikiMed Electron custom app:

* WikiMed by Kiwix Linux and Windows Electron app: https://kiwix.github.io/kiwix-js-pwa/wikimed

The tile needs to show that the app is for **Linux** as well as **Windows**.

Could I suggest a better solution than separating the custom tiles by OS? I suggest having "Electron" available in the dropdown for custom apps. Electron is a universal technology for Linux, Windows and macOS (but I currently only build it for Linux and Windows, as I don't have a Mac to test on), so it doesn't easily fit the paradigm of division by OS.

**Comment by Popolechien** [comment]
Added Electron to Wikimed for Windows and created a Wikimed for Linux box.

I would rather think that users (or potential users) first consider the platform they're on and _then_ pick which tech works best for them, not the other way around 😉
