### ISSUE TITLE
Change tile for Wikivoyage (Electron) custom app

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/web#221]
@Popolechien  Same as for #220, with the following Wikivoyage permalink:

* Wikivoyage by Kiwix Linux and Windows Electron app: https://kiwix.github.io/kiwix-js-pwa/wikivoyage

Again, I feel it would be best to have an Electron dropdown for the custom apps, and have this tile belong to that category. It is currently for Linux and Windows, but could be extended to macOS in the future.

**Comment by Popolechien** [comment]
Done! 
Regarding the dropdown menu we can only assign it to a given platform (windows, linux, etc.) in our custom WP backend.
