### ISSUE TITLE
Tweak description of Kiwix JS PWA on Windows tile

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/web#222]
Some slight suggested tweaks, with insertions in italics, and deletions crossed out:

> # ~Compatible With Older Versions (Windows XP, Vista, Etc.)~ _Installable Web app (works on older Windows too)_
> Kiwix JS PWA is a smaller alternative. It can be used as an offline-first Progressive Web App in your browser. There is a also _a_ Windows Store (UWP) version for Windows 10 or 11 tablets, phones, PC and Xbox, and an Electron ~versions~ _app_ compatible with ~older~ _all_ Windows _versions_ (XP, Vista, Win7/8/10/11) .

_Originally posted by @Jaifroid in https://github.com/kiwix/web/issues/217#issuecomment-1763338144_

**Comment by Popolechien** [comment]
I would disagree with that one. Again, mentioning something as arcane as _Installable Web App_ to someone stuck with Windows XP or Vista is like speaking Greek to them (it certainly would be to me).
From a user point of view the question is "_I've got old stuff, do they have anything for me?_"

**Comment by Jaifroid** [comment]
OK.
