### ISSUE TITLE
demo.hotspot.kiwix.org returns error "This site can’t provide a secure connection"

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#231]
I get the following screen when trying to reach [demo.hotspot.kiwix.org
](http://demo.hotspot.kiwix.org/)![Screenshot 2024-08-15 at 17 07 33](https://github.com/user-attachments/assets/4f2da694-4f2b-4d1f-adfa-0552bed63da2)

That is on Chrome for macOS
Screen remains blank on Firefox and Duckduckgo on Android

**Comment by rgaudin** [comment]
As indicated in `#uptime` channel, I am currently transferring the demo to the new server. It's gonna take a few hours. Check tomorrow
