### ISSUE TITLE
Could server side cron jobs be enabled for Wordpress / FluentCRM?

### ISSUE THREAD

**Issue by anupulu** [kiwix/web#233]
I have tried to set up an [automation](https://kiwix.org/wp-admin/admin.php?page=fluentcrm-admin#/funnel/2/edit) in Wordpress that does this:

1. **Trigger**: User signs up to Kiwix newsletter after the most recent one has been sent (=user record is created in FluentCRM after a certain date)
2. After waiting for 14 days after signup and until a selected future date, the automation should send that user the most recent newsletter.

The goal is that all users would receive a newsletter within a reasonable time after signup - either the most recent one, or the next one.

But it seems like the automation is not working.
I'm able to manually add users to the automation funnel by a few clicks (which I have done), but that kind of manual work defeats the purpose of having automation.

[Here](https://kiwix.org/wp-admin/admin.php?page=fluentcrm-admin#/settings/settings_tools), I can see that the automation should be running once per hour, but for some reason the automation I set up doesn't get triggered.

I can see a warning text suggesting that "Server Side Cron is not enabled. Please consider enabling server side cron. [Read more about server side cron here.](https://fluentcrm.com/docs/fluentcrm-cron-job-basics-and-checklist/)" and I think that might be the cause of the issue.

Could you take a look and let me know what could be done here, to make the automation work?
Thank you. :)

**Comment by rgaudin** [comment]
I've enabled it following that documentation. The Settings/Tools of FluentCRM seem to confirm its working.
