### ISSUE TITLE
wiktionary versions indistinguishable

### ISSUE THREAD

**Issue by ynikitenko** [kiwix/web#234]
When [searching](https://library.kiwix.org/#lang=eng&category=wiktionary) for a Kiwix Wiktionary in English, I get four results:

![Image](https://github.com/user-attachments/assets/b60e7093-4bed-406c-8225-e68e771a3444)

Two of these results are with images, two are without. But that could be seen only through the link: the representation of them on the page is indistinguishable. Otherwise it is unclear why the sizes are different.

How to fix: add a distinguishing text "no images" and "with images" to the corresponding versions.

**Comment by kelson42** [comment]
Yes, this is clarly a problem but handled already with https://github.com/kiwix/libkiwix/issues/421

**Comment by ynikitenko** [comment]
Thank you. Honestly, that could be also simply solved through the Web version (the original ticket has been unresolved for quite a while).

**Comment by kelson42** [comment]
@ynikitenko library.kiwix.org is nothing else than a kiwix-serve, this is the reason. But I agree that it makes a very long time without a fix for this important bug.
