### ISSUE TITLE
Indicate full language names on zim list

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#24]
Expand shorthands to the language's full names at http://wiki.kiwix.org/wiki/Content_in_all_languages

ar -> arabic, en -> english, etc.

**Comment by kelson42** [comment]
I could not replace the language column code by the full name as this is a search/filter key... but I have put the full language name in parenthesis beside the content name. Hope that is good enough.

**Comment by Popolechien** [comment]
Ok thanks, I guess that'll do - but is there a reason some languages are explicit while others still have a filter key?

**Comment by kelson42** [comment]
@Popolechien I suspect somehow the library delivering the service does not have the matching :( As all of this is going to disappear at some point, I think we should not invest too much of energy on this.

**Comment by Popolechien** [comment]
@Kelson Great. Do we have a timeline in mind for that?

**Comment by kelson42** [comment]
No, I think that we should build the filtering in kiwix-serve and the allow people to download things directly from the kiwix-serve welcome page interface. Then that wiki page will become useless.

**Comment by kelson42** [comment]
This is finally here at https://library.kiwix.org, sorry it has taken so long.
