### ISSUE TITLE
404 on almost all pages of kiwix.org

### ISSUE THREAD

**Issue by sivaraam** [kiwix/web#26]
I get a 404 for almost all pages of kiwix.org

This includes,

http://www.kiwix.org/downloads/

http://www.kiwix.org/kiwix-plug/

http://www.kiwix.org/cuba/

and a lot more.

**Comment by Popolechien** [comment]
Yup saw that, looks like the WPML update weirded out. Trying to fix it.

**Comment by Popolechien** [comment]
Fixed. Apparently the last round of updates misconfigured the .htaccess file.
