### ISSUE TITLE
Create a "donate" web page

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#29]
I think it would be nice to have a "donate" web page which would offer the following advantages over the paypal footer we have already:
* Explain a bit how the Kiwix association use/need money
* Provide IBAN/BIC to allow people to give directly (without having high Paypal fees)

**Comment by Popolechien** [comment]
Done: www.kiwix.org/support

**Comment by kelson42** [comment]
@Popolechien Great, thx!
