### ISSUE TITLE
bad OSX icon

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#3]
Le nouveau est https://en.wikipedia.org/wiki/OS_X#/media/File:OS_X_El_Capitan_logo.svg

**Comment by automactic** [comment]
macOS Sierra doesn't have a round icon, the closest I could find is this
![screenshot 2016-09-20 09 17 08](https://cloud.githubusercontent.com/assets/8294252/18671793/7bca6be2-7f13-11e6-8343-221e437fbac2.png)

**Comment by automactic** [comment]
Use [this](http://a4.mzstatic.com/us/r30/Purple71/v4/3c/68/c9/3c68c9dc-6b8d-d1c6-edb6-5dfd11ff8539/icon128-2x.png) from [here](https://itunes.apple.com/us/app/macos-sierra/id1127487414?mt=12)

**Comment by Popolechien** [comment]
The macOS wordmark is [here](https://commons.wikimedia.org/wiki/File:MacOS_wordmark_(2017).svg) but in any case the desktop app is not functional anymore and been removed from the website.
I'll close the issue for now.
