### ISSUE TITLE
Small usability issue with www.kiwix.org/lang/downloads/ links

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#31]
The links behind the content icons lead to the respective online web sites. IMO this is a bit misleading.

I think they should lead the "complete" ZIP file as this is why people are there on this "Download" page.

The link to the online version of the content might be a good idea, but I would put it then as an "online version" link at the end of the small description text.

**Comment by Popolechien** [comment]
Disagree. People need to have a way to find out what these contents look like - pretty obvious for Wikipedia, but a lot less for the others as they are not as famous.
I'll leave the request open for the time being, the frontend is anyway being re-written by Martin so this is bound to change one way or the other.

**Comment by kelson42** [comment]
This request is not about removing a link to the online reference. This request is about removing it from the most obvious clickable item.

**Comment by Popolechien** [comment]
Fixed.
