### ISSUE TITLE
Retire/archive http://blog.kiwix.org/

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#32]
Blog hasn't been update for the past 5 1/2 years ^^

**Comment by kelson42** [comment]
Hmmm... you are probably right. I give me a bit of time to think about that.

**Comment by martin8032** [comment]
My point of view: Why should we maintain a website AND a blog? We can easily add a «Blog» or «News» section to our website if required.

**Comment by kelson42** [comment]
@martin8032 I think we all agree on that. I'm just a bit nostalgic. Will fix it.

**Comment by kelson42** [comment]
@martin8032 @Popolechien After the discussions of last days, I'm seriously thinking about relaunching the blog - at least for tech announcements. Beside having a channel to make announcements complementary to offline-l mailing list, it would allow for example to fix https://github.com/kiwix/maintenance/issues/102 and https://github.com/kiwix/web/issues/101.

**Comment by Popolechien** [comment]
Not a bad idea. I would keep the old blog solution for the time being - after maybe archiving the old material. I would need access to it though, and do we have statistics by any chance?

**Comment by kelson42** [comment]
Yes, we have stats but the whole solution is really primitive (old). If we agree on this approach I will start to publish there and in the next few months we could maybe figure out how to have a blog/new part on our web site?

**Comment by Popolechien** [comment]
Yep, I wouldn't put too much time or resources on blogging, it is mostly a gone type of platform. Alternatively, we could also use the Space platform from the Wikimedia Foundation which would guarantee a minimal audience to start with.

**Comment by kelson42** [comment]
@Popolechien The space is a good idea... We can copy/publish content there too.

**Comment by martin8032** [comment]
Adding a blog/news section to our website www.kiwix.org is easy – it's WordPress, and WordPress was initially developed for exactly that purpose. To migrate the old content might be harder, though – I am not especially keen on doing that.

@Popolechien I do not agree about «blogging is gone» – the term is not that popular anymore, but publishing news online is still around, IMHO.

**Comment by kelson42** [comment]
If the blog is available on www.kiwix.org I will use it. I could migrate the old content to our wiki.

**Comment by martin8032** [comment]
Please enter some blog posts at https://www.kiwix.org/wp-admin/edit.php (as POSTS, not as PAGES). As soon as we have some content ready I will activate the blog in the frontend.

**Comment by kelson42** [comment]
I have backuped old Blog at https://wiki.kiwix.org/wiki/Blog. But not sure where http://blog.kiwix.org should exactly redirect... Will try to write a first blog post to see the publishing details/URLs.

**Comment by martin8032** [comment]
https://www.kiwix.org/en/blog/ should work.

**Comment by kelson42** [comment]
@martin8032 I have deleted old blog and put a redirection. Blog post to come soon. Thank you very much for your quick help on this!
