### ISSUE TITLE
Remove UX job posting from Opensourcedesign.net

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#33]
https://opensourcedesign.net/jobs/jobs/2018-02-17-ux-designer-contracted

We're still receiving applications ^^

**Comment by kelson42** [comment]
@Popolechien Have asked on IRC, hope this will be enough.

**Comment by kelson42** [comment]
Done https://github.com/opensourcedesign/opensourcedesign.github.io/issues/177#event-1721530650
