### ISSUE TITLE
Add captcha to feedback page.

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#35]
Namely http://input.kiwix.org/

95% of the emails we get from there are Russian pr0n :-/

**Comment by kelson42** [comment]
I reopen... as long we do not fully have an alternative.

**Comment by Popolechien** [comment]
Might as well shut it down and put a redirect to https://www.kiwix.org/contact/ - 15 out of 15 emails received in the past 24hrs are spam. It's intensely annoying.

**Comment by Bhavnaharitsa** [comment]
I want to work on this issue

**Comment by kelson42** [comment]
@Bhavnaharitsa Thank you for proposing your help, but this but is meanwhile invalid as we have migrated to a new solution for the feedback and this solution already has a captcha system.
