### ISSUE TITLE
Create Ambassadors mailing list

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#36]
I need to keep in touch and inform our ambassadors about new developments. They're pretty much a good population for beta testing of new releases.

**Comment by kelson42** [comment]
@Popolechien Would you be able to give a try to https://gaggle.email/ ?

**Comment by kelson42** [comment]
https://gaggle.email/ does the job, you just need to organize the build to avoid advertisement. I plan to migrate other mailing lists afterward.
