### ISSUE TITLE
 Put warning banner on top of wiki that indicates new zim files are not compatible with 0.9

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#38]
I've had many complaints of "file not found" and people ought to know (or at it we should warn them) about what to do, not do, and expect.

A simple "New zim files post May 2018 do not work on Kiwix for Windows/Linux" should suffice.

**Comment by Bhavnaharitsa** [comment]
I would like to contribute on this issue

**Comment by kelson42** [comment]
@Bhavnaharitsa Go ahead, you should be able to do that by customizing http://wiki.kiwix.org/wiki/MediaWiki:Sitenotice

**Comment by kelson42** [comment]
@Popolechien This is not necessary anymore
