### ISSUE TITLE
bad ios icon on www.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#4]
good one https://www.apple.com/ios/ios-10/overview/developer/beta/icon_large_2x.jpg

**Comment by kelson42** [comment]
<img width="569" alt="screenshot 2016-09-19 16 48 21" src="https://cloud.githubusercontent.com/assets/1029718/18658628/133c1070-7f05-11e6-8dc1-659001ba8f4b.png">

**Comment by automactic** [comment]
I found a better one. https://commons.wikimedia.org/wiki/File:IOS_logo.svg

**Comment by Popolechien** [comment]
Done.

**Comment by automactic** [comment]
looks good!
