### ISSUE TITLE
Retire zip link from wiki.kiwix.org

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#53]
Most pages still have a link to the zip (0.9+zim) bundle and need to be or updated, starting with the big "download Kiwix button"
![capture d ecran 2019-02-15 a 09 54 01](https://user-images.githubusercontent.com/21675885/52845547-b1db9280-3107-11e9-88b4-ebbc57e85078.png)

**Comment by kelson42** [comment]
doing...

**Comment by kelson42** [comment]
Done
