### ISSUE TITLE
Loading issue wiki.kiwix.org

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#54]
When trying to connect to wiki.kiwix.org the load time is unusually long (about 10-15 seconds to get to the landing page).
I got the following error message once (could not reproduce)
![capture d ecran 2019-02-15 a 09 51 42](https://user-images.githubusercontent.com/21675885/52845398-527d8280-3107-11e9-9efc-360818688943.png)

[42f43d7ed1f3dfaee00f1099] 2019-02-15 08:48:02: Erreur fatale de type « Wikimedia\Rdbms\DBQueryError »

I also tried Pingdom (https://tools.pingdom.com) and got a pageload time of **46 seconds**
![capture d ecran 2019-02-15 a 09 55 43](https://user-images.githubusercontent.com/21675885/52845683-fcf5a580-3107-11e9-9633-3ca22a6b326a.png)

[Google's pagespeed](https://developers.google.com) simply timed out.

**Comment by rgaudin** [comment]
I've been affected by this as well the other day.

**Comment by kelson42** [comment]
This has been fixed.
