### ISSUE TITLE
HTTPS does not work properly on new www.kiwix.org website

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#58]
With https://www.kiwix.org/en/home/, Firefox complains about dependences not loaded in HTTPS.

**Comment by rgaudin** [comment]
Reason is the favicon link to: `http://www.kiwix.org/wp-content/uploads/kiwix_visual_512x512.png`

**Comment by kelson42** [comment]
@Popolechien Any chance you can fix this link?

**Comment by Popolechien** [comment]
I do not have permissions but pinged the Power That Be.

**Comment by kelson42** [comment]
@Popolechien He as a github account?

**Comment by martin8032** [comment]
@kelson42 @Popolechien He has. And he fixed the issue already. Please test.

(Fun fact: Chrome does not complain about a favicon which uses HTTP instead of HTTPS – only Firefox does.)

**Comment by kelson42** [comment]
@martin8032 Thx, works fine for me
