### ISSUE TITLE
Spelling Issues (EN)

### ISSUE THREAD

**Issue by Macavirus** [kiwix/web#59]
I didn't crawl the whole site, but here are some English language spelling corrections:

## On https://www.kiwix.org/en/downloads/

> The KIWIX Reader allows you to use content packages in the ZIM format. It is available for all mayor operating systems. It comes as a standalone application or as a browser plug-in. Simply choose the KIWIX Reader that suits you best.

should be:

> The KIWIX Reader allows you to use content packages in the ZIM format. It is available for all **major** operating systems. It comes as a standalone application or as a browser plug-in. Simply choose the KIWIX Reader that suits you best.

## On https://www.kiwix.org/en/about/

> ICT infrastructure: In developing countries and in rural areas internet access is often slow, unreliable, or not available at all. This may also be the case in periods of natural desasters, uprisings, or war.

should be

> ICT infrastructure: In developing countries and in rural areas internet access is often slow, unreliable, or not available at all. This may also be the case in periods of natural **disasters**, uprisings, or war.

and
> Affordability: Many People with low or no income simply cannot afford internet access.

should be

> Affordability: Many **people** with low or no income simply cannot afford internet access.

## On https://www.kiwix.org/en/downloads/kiwix-content-packages/

> If you are a company or an organisation that whishes to distribute web content for offline usage then we are happy to help. Our team will crawl and package your content too.

should be

> If you are a company or an organisation that **wishes** to distribute web content for offline usage then we are happy to help. Our team will crawl and package your content too.

**Comment by kelson42** [comment]
@Macavirus Thank you for reporting this!
@Popolechien Can you please have a look and fix the text if problems are confirmed?

**Comment by Popolechien** [comment]
@Macavirus Thanks a lot!
Typos have been fixed - there should be a bit of a rewrite happening over the next few weeks, but it does not hurt to have clean text ^^
