### ISSUE TITLE
Re-configure www.kiwix.org to deal with stats.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#60]
This does not work anymore since the introduction of v2 in February. Martin had it in plan and was not having access to the Admin UI of Matomo. This has been fixed my me last week, so we could carry on I suppose.

**Comment by kelson42** [comment]
@Popolechien @martin8032 Any news on that?

**Comment by martin8032** [comment]
Done. Please check.

**Comment by kelson42** [comment]
@martin8032 Thank you. Seems to work fine :)
