### ISSUE TITLE
Link wiki.openzim.org and kiwix.openzim.org donate button to www.kiwix.org/donate

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#63]

**Comment by Popolechien** [comment]
Here is the code given by donorbox, but I couldn't figure out where to add it / replace the paypal one:`
```<a class="dbox-donation-button" href="https://donorbox.org/kiwix?amount=25&hide_donation_meter=true" style="background:#2d81c5 url(https://d1iczxrky3cnb2.cloudfront.net/red_logo.png) no-repeat 18px center; color: #fff;text-decoration: none;font-family: Verdana,sans-serif;display: inline-block;font-size: 16px;padding: 13px 17px 13px 56px; -webkit-border-radius: 2px; -moz-border-radius: 2px; border-radius: 2px; box-shadow: 0 1px 0 0 #1f5a89; text-shadow: 0 1px rgba(0, 0, 0, 0.3);" >Support us!</a>```

**Comment by kelson42** [comment]
@Popolechien Thank you. I have made the necessary modifications. Done.
