### ISSUE TITLE
iOS/MacOS logos are "ugly" on https://www.kiwix.org/en/downloads/kiwix-reader/

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#69]
... and they are the same for both...

I propose for iOS:
https://wiki.kiwix.org/w/images/5/5e/IOS_Logo.png

I propose for MacOS:
https://wiki.kiwix.org/wiki/File:Macosx_logo.png

**Comment by Popolechien** [comment]
Uh, I probably lost 1/10 of my eyesight by looking at your iOS logo o_0
I'm all cool for improving looks, but it seems to me the official apple logo (at least currently) is the full black thing (which for the record I do not find "ugly").

**Comment by kelson42** [comment]
@Popolechien With need a different and adequate logo fro iOS and MacOS, the logo of Apple has "nothing" to do here.

**Comment by rgaudin** [comment]
Agrees having different ones is better but we need higher resolution ones. The iOS one is pixilated on my old screen at 1x.

**Comment by martin8032** [comment]
I agree that there is room for improvement here. But the image resolution is my least concern.

First and foremost we must respect Apple's guidelines for using their intellectual property:
https://developer.apple.com/app-store/marketing/guidelines/

We then should only use official, current logos. I didn't do a thorough research yet, but I'm not convinced that Apple actually has icons for these OS. This needs further investigation.

BTW: Apple has announced that iOS for the iPad will be called iPad OS in the future, so we are actually talking about three, not only two logos.

**Comment by kelson42** [comment]
@martin8032 We don't have to respect what is written there, they are **guidelines**. They are guidelines for the app stores, which is not the only way to distribute Apple software (that said it is quite difficult to avoid that for iOS, but no problem for MacOS). We do distribute a `dmg` for MacOS on this page.

The icons of the OS are semantically the best thing to put at this place on this page. But like you said, and this was our conclusions years ago, there is no or no stable icon for MacOS and iOS. That is why I had these recommendations which are not official but at least fancy and different from the company logo.

So, what we know after all of this discussion, is that they is no quick/easy solution.

I extend my first proposal:
* My first proposal of alternative logo (find a better resolution for iOS logo)
* Replace the two logos with respective iTunes/App Store logos
* Pick one in each of https://commons.wikimedia.org/wiki/Category:MacOS_logos and https://commons.wikimedia.org/wiki/Category:IOS_logos

**Comment by martin8032** [comment]
How about these?

https://www.kiwix.org/en/downloads/kiwix-reader/

**Comment by rgaudin** [comment]
Looks good to me

**Comment by Popolechien** [comment]
Yep, @kelson42 can we close that ticket?

**Comment by kelson42** [comment]
Well done
