### ISSUE TITLE
"Kiwix Hotspot" Web page has a layout problem on my tablet

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#71]
The content has a left margin far to high. See the screenshot.

![FireShot Capture 023 - Kiwix Hotspot – Kiwix - www kiwix org](https://user-images.githubusercontent.com/1029718/61460053-4aec2f00-a96e-11e9-82ac-3f73b6fe0a88.png)

**Comment by Popolechien** [comment]
Confirm - I have the same issue here and I'm probably the culprit as I can see I can move the frame, but cannot bring it back to where it was :-/

**Comment by martin8032** [comment]
It looks like this little accident happend a long time ago. I had to revert the page to my last version from  the end of February. Can someone please re-do the text updates?

**Comment by Popolechien** [comment]
Yep no problem, will do. Closing this specific issue. Thanks Martin.

**Comment by kelson42** [comment]
@martin8032 thx

**Comment by kelson42** [comment]
I re-open the ticket as the page is not in the state it should be. We don't have the links to the binarires for example, etc...

**Comment by Popolechien** [comment]
Yeah that one is for me.

**Comment by kelson42** [comment]
@Popolechien Might that be that everything is fixed now?

**Comment by Popolechien** [comment]
Looks like it is to me.
