### ISSUE TITLE
Wrong Kiwix Desktop link for GNU/Linux

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#72]
"Kiwix for GNU/Linux – 64 bit binaries" underlying link is wrong on https://www.kiwix.org/en/downloads/kiwix-reader/.

It is http://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64.tar.gz and it should be https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_x86_64.appimage

**Comment by martin8032** [comment]
Done. Please double-check.

**Comment by kelson42** [comment]
@martin8032 Perfect. Thx.
