### ISSUE TITLE
Kiwix-serve page should provide links to binaires

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#73]
At https://www.kiwix.org/en/downloads/kiwix-server/

* Windows X86 64 bits https://download.kiwix.org/release/kiwix-tools/kiwix-tools_win-i686.zip
* GNU/Linux X86 64 bits https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64.tar.gz
* GNU/Linux X86 32 bits https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-i586.tar.gz
* GNU/Linux ARM https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armhf.tar.gz

**Comment by martin8032** [comment]
Done.

**Comment by kelson42** [comment]
@martin8032 Thx, I made a typo and you made the same: "binaires" shoudl be "binaries"... but in fact it would be just better to write only "Download" IMO.

**Comment by martin8032** [comment]
It's now «Downloads».

**Comment by benjaoming** [comment]
Great work @martin8032 

One small amendment:

> Kiwix-Serve needs to be installed from the Kiwix-tools suite.

Could perhaps be:

> `kiwix-serve` is provided as a self-contained binary by the `kiwix-tools` suite, which you can download below.

**Comment by martin8032** [comment]
Like this? Or is the non-proportional font important as well?

**Comment by benjaoming** [comment]
@martin8032 you can be the judge of that. If there is a style for `<code>` tags, I think it's worth pointing out when a name is in fact also a command.. but for this, it's pretty obvious :)

**Comment by benjaoming** [comment]
And thanks for updating!

**Comment by martin8032** [comment]
Since this website tries to address non-nerdy people I think we should keep things simple and talk about products, not commands here.
