### ISSUE TITLE
Kiwix-server page should be rename to "Kiwix-serve"

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#74]
This is the real name of the software.

**Comment by martin8032** [comment]
Strange name. However, I changed the title – and the URL accordingly, which is therefore:

https://www.kiwix.org/en/downloads/kiwix-serve/

**Comment by kelson42** [comment]
The link on the homepage is dead. A redirect kiwix server->kiwix serve would solve it.

**Comment by martin8032** [comment]
We are probably talking about the link in the footer. It's fixed by now.

**Comment by kelson42** [comment]
@martin8032 On https://www.kiwix.org/en/downloads/ the link to Kiwix-Serve is broken too. I thought we had a solution to detect broken link within Wordpress?

**Comment by martin8032** [comment]
We have, but obviously it cannot check links which are part of a Divi button.

I fixed the link manually and I opened a ticket in the support forum (https://wordpress.org/support/?post_type=topic&p=11911383).

**Comment by kelson42** [comment]
@martin8032 Thx
