### ISSUE TITLE
Add Stéphane to the team

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#75]
At https://www.kiwix.org/en/about/the-kiwix-team/, add our new Board President.

**Comment by Popolechien** [comment]
Fields have been updated (and simplified). 
We still miss images, I've sent requests.

**Comment by kelson42** [comment]
@Popolechien At least you master the color filter ;)

**Comment by kelson42** [comment]
@Popolechien Should we close that one. Looks better meanwhile.

**Comment by Popolechien** [comment]
Yep, everyone should be there now (save 2, but I've asked and eventually they'll come around with pics)
