### ISSUE TITLE
https://www.kiwix.org/en/downloads/ links to kiwix-desktop are not permalinks

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#76]
As a consequent they point to an older version of Kiwix Desktop :(

**Comment by Popolechien** [comment]
@kelson42 where is the list of permalinks again? or the general structure?

**Comment by kelson42** [comment]
@Popolechien they are properly implement in this page https://www.kiwix.org/en/downloads/kiwix-reader/

**Comment by Popolechien** [comment]
Corrected.
