### ISSUE TITLE
Export list of contents to excel sheet

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#77]
There is a widget on Wordpress that would allow us to filter / sort the list of contents currently available at https://wiki.kiwix.org/wiki/Content_in_all_languages
It works off an Excel sheet - I've tried exporting the web page as is but excel won't reproduce the existing hyperlinks (meaning that HL appear as hard text; Word, strangely enough, does work fine). Any help there?

**Comment by martin8032** [comment]
I'm not sure if I fully understand what you are trying to achieve, but after we are making good progress with the atom feed: What do we need this for?

(And by the way: What WordPress widget are we talking about?)

**Comment by Popolechien** [comment]
Well I was referring to something you showed on Wednesday where we could sort content from an imported excel table.
Regarding the feed, I would see it better used for updates on our Twitter feed.

**Comment by kelson42** [comment]
@Popolechien Like @martin8032, the std catalog format is the OPDS/Atom feed. If this is not fitting to the needs then we can improve it/have a look again to the problem. But Martin seems happy so far with what we provide already as interface. I think you are refering to the ability to export widgets, the ticket I was talking about is here https://github.com/kiwix/kiwix-tools/issues/55.

Can we close this one?

**Comment by Popolechien** [comment]
@kelson42 I don't think #55 is relevant to the case at hand. At this stage I'm just asking for something marginally better than what's on wiki but that we can put up on our website.

**Comment by kelson42** [comment]
@Popolechien Ok! so lets forget about Excel first.
@martin8032 I let you deal with @Popolechien's needs. Let me know if you need something more on library.kiwix.org side.

**Comment by martin8032** [comment]
@Popolechien I'm not sure if I understand what this issue is all about. Please provide more details or – if this export function is no longer needed – close the ticket.

**Comment by Popolechien** [comment]
@martin8032 Basically I would like the list currently on wiki to be served on the website BUT with some sort of sort menu selector for languages and type of content (all, nopic, mini).

**Comment by martin8032** [comment]
If we have data in an excel sheet, there are ways to import and display this data on a WordPress website – no question about this. And we will also find a way to provide some search and filtering options.

I have probably mentioned https://de.wordpress.org/plugins/participants-database/ which I use here https://www.klinische-dozenten.ch/vereinigung/mitglieder/, but there are other solutions as well.

BUT: This looks like a manual process. Who has the time to maintain this? That's why using Emmanuel's feed sounds like a better alternative to me.

**Comment by Popolechien** [comment]
Well the feed described is for Kiwix-serve (meaning to access zim content), I want something to access the zim files themselves (for download), which is slightly different. This is for a limited set of users I guess (macOS and Kiwix-JS) but nevertheless needs to be done.
The manual/labour issue is more problematic indeed, but then if it is to be done once or twice a year we probably can manage.
@kelson42 is there a way to export [this table](https://wiki.kiwix.org/wiki/Content_in_all_languages) on our wiki as a CSV file?
