### ISSUE TITLE
Switch www.kiwix.org from TranslatePress to WPML

### ISSUE THREAD

**Issue by martin8032** [kiwix/web#78]
As discussed in our meeting of 24th July we will migrate our website from TranslatePress back to WPML as the multilingual platform.

**Comment by martin8032** [comment]
FYI: We are currently evaluating a WPML alternative based on https://www.smartcat.ai. So this issue is not as stale as it looks.

**Comment by martin8032** [comment]
You will notice that all languages except English are gone from our website as of today. This is not a bug – it's a feature! It means that I have replaced TranslatePress by WPML and that we are ready to enter (or re-enter) translations.

Since this GitHub repo is public I will not share all the details here. Instead, I will send instructions for translators to @Popolechien ASAP.

BTW: All existing translations are still available, so we don't have to retranslate anything.

**Comment by kelson42** [comment]
@martin8032 That sounds like a good news. I guess this is an enabler to have a more inclusive collaboration with www.kiwix.org translators. Who is going to copy the already translated strings?

**Comment by martin8032** [comment]
The translators themselves, because if you don't know the language really well you have no chance to enter the right translation at the right place.
