### ISSUE TITLE
RSS feed for new updated zim dumps

### ISSUE THREAD

**Issue by fturco** [kiwix/web#8]
I'm not aware of any way for being notified of new updated zim dumps. What about an RSS feed?

**Comment by kelson42** [comment]
Here a "short" answer:

1 - We just have started to create ZIM files with a unique meta data identifier (over time) to allow to to identify updates. Still a pilot only a few files have it.
2 - We provide a custom XML library here http://download.kiwix.org/library/library.xml. Only a few ZIM files have the "name" (unique) attribute.
3 - Next Kiwix for iOS will then start to take care about this new field. Next will be Android version.

That said, in the future we will abandon this old/custom XML stream to create an OPDS one. I have created the corresponding feature request https://github.com/kiwix/kiwix/issues/342. One time implemented the reader will have to be upgraded to deal with it.

Hope this answer your question.
