### ISSUE TITLE
library.kiwix.org returns error 502

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#80]
also question: why so often?

**Comment by kelson42** [comment]
The situation has been improved, but it still happen time to time that the serive is not available... so problem is not fully solved.

**Comment by kelson42** [comment]
It is really rare meanwhile, but we have persisting speed problem with multi-zim search and snipped retrieval.

**Comment by kelson42** [comment]
Caused by https://github.com/kiwix/maintenance/issues/85
