### ISSUE TITLE
Clear download.kiwix.org/hotspots/ 

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#81]
There's about 1.5Tb of data here that is not being used anymore: everyone it was created for now has a cardshop access.

I would now reserve the directory for content to be distributed via the cardshop page.

**Comment by rgaudin** [comment]
You mean http://download.kiwix.org/hotspots/ ?

**Comment by Popolechien** [comment]
woops yes :-)

**Comment by kelson42** [comment]
Ok, do we know that this is not used?

**Comment by Popolechien** [comment]
Well we can ask Jorge, Florence and the Orange Foundation, but I have my doubts. Also if we need/want to keep archives I'd rather move these to /old and keep this directory for contents we actively distribute.

**Comment by kelson42** [comment]
I move this to the cardshop repo, the management of images should be solved there. It is partly a technical and partly a strategical decision.
