### ISSUE TITLE
Create a preliminary cardshop

### ISSUE THREAD

**Issue by martin8032** [kiwix/web#82]
As requested by @Popolechien we will create a simple shop (based on Easy Digital Downloads) to sell a small selection of image files for Kiwix Hotspot online.

**Comment by Popolechien** [comment]
Here's the rough sketch:
![Capture d’écran 2019-08-08 à 15 25 39](https://user-images.githubusercontent.com/21675885/62706964-d3e80a80-b9f0-11e9-9b3b-8313c8e5d8fc.png)
This will not give access to the Cardshop, but allow users to directly pay and get a download link for a ready-made hotspot image (ie without us having to do anything for them).
We will need to create three hotspot images: one in English, one in German, and one in Spanish (based on our dominant customer demographics). 
I unfortunately cannot import the JSONs, but the idea is to have basic images with Wikipedia+Wiktionary (Maxi/novid) on each card (+Raspberry Stackexchange on the English card as a secret bonus).
Once they pay, users should be get two links to chose from: 
- a regular http one (presumably hosted on a private version of download.kiwix.org/hotspots);
- a bittorrent link so as to save on bandwidth costs for us.

**Comment by martin8032** [comment]
Current status:
- The shop is implemented in the production environment: https://www.kiwix.org/en/downloads/kiwix-cardshop/
- The URLs for the downloads are missing.
- The payment plugin is missing.
- The page is visible but not linked in the menu and should not be indexed by search engines.

**Comment by kelson42** [comment]
@Popolechien We should have a free offer here. It is just the mockup which does not take it in account?

**Comment by Popolechien** [comment]
Yes that's the sales part. The demo image will be addressed in a separate ticket.

**Comment by kelson42** [comment]
The technical project is started here https://github.com/kiwix/cardshop/projects/1. Not sure about the value of this ticket and what we should do with it.

**Comment by Popolechien** [comment]
This is a separate project aimed at downloading standardized content without registration (as opposite to full access to the library for bespoke images). Partly covered by [#112](../../cardshop/issues/112) and [#117](../../cardshop/issues/117). Now that enwp is out I'll try and release a test version shortly.

**Comment by Popolechien** [comment]
Sorted! www.kiwix.org/en/cardshop-access
