### ISSUE TITLE
Add the ubuntu ppa in the install possibilities

### ISSUE THREAD

**Issue by LAfricain** [kiwix/web#84]
Please add [lafricain PPA](https://launchpad.net/~lafricain79/+archive/ubuntu/lafricainenvrac) in the install alternative for Ubuntu.
The ppa is the only way to have a 32 bit package.
Or link the website page to the [doc ubuntu kiwix page](https://doc.ubuntu-fr.org/kiwix).

**Comment by Popolechien** [comment]
This is kiwix-desktop_2.0 beta5 version, we just release RC1. Can you please upadate it (final release should come at the end of the Summer, I'm told)?
@kelson42 Any comments? I'm not super familiar with Linux things.

**Comment by LAfricain** [comment]
I just update the RC2.
Please add now a link to the [ppa](https://launchpad.net/~lafricain79/+archive/ubuntu/lafricainenvrac).

**Comment by Popolechien** [comment]
Done.

**Comment by kelson42** [comment]
I'm strongly again putting links to binaries repo Kiwix does not control tightly.

**Comment by LAfricain** [comment]
What do you mean by: "clear strategy regarding this has not been identified"? You can check every thing you want on the ppa, the source are available (and it's your sources of course).

**Comment by kelson42** [comment]
For now, the best we can/should do, is probably in the REAMDE in the Git repo, make a link, indicating this is a "contribution" (so not handled by Kiwix team). So this is clear for everyone that we are not responsible of it.

But on the longer term, the best we could do, is publishing our own PPA and adapting our release process so this is taken in account.

**Comment by LAfricain** [comment]
> the best we could do, is publishing our own PPA

Yes. All is ready you have just to pick what you want on mine.

**Comment by kelson42** [comment]
We are currently launching our own PPA with @legoktm at https://bugs.launchpad.net/ubuntu/+source/kiwix. @LAfricain This hopefully will save your time in the future.

**Comment by LAfricain** [comment]
The link seems to be wrong. I can't find the ppa, I'm sent on the bugs page of launchpad.

**Comment by kelson42** [comment]
the effort is ongoing, should come soon.
