### ISSUE TITLE
wmch kiwix web page contains a dead link to our web site

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#85]
https://www.wikimedia.ch/projects/kiwix-wikipedia-offline/

**Comment by martin8032** [comment]
I'm no longer in charge of that website. But we can easily put a redirect on our side to solve the problem. And as far as I see this has already happened.

**Comment by kelson42** [comment]
@martin8032 Thank you for your offer of redirect, but a fix in the original page would be better. @Popolechien Do you know who to ask for it?

**Comment by Popolechien** [comment]
I'll ping them.

**Comment by Popolechien** [comment]
Fixed.
