### ISSUE TITLE
Library returns 502 error

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#86]
This is fairly recurrent. Any idea why this happens?

**Comment by kelson42** [comment]
@Popolechien This is a loss of time to open the same bug many times. You have open one already 20 days ago here #80 and the problem is well known and @mgautierfr works on the solution.

**Comment by Popolechien** [comment]
@kelson42 I know, but how will I flag that it went down and ask for a refresh/restart/reboot? Unless you tell me it will restart of its own volition and I should come back a couple of hours later when I have this issue, I need to flag it, don't I?

**Comment by kelson42** [comment]
@Popolechien Slack please.
