### ISSUE TITLE
Remove link to kiwix-plug wiki article

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#89]
> Please refer to the Kiwix Wiki for more information.

at https://www.kiwix.org/en/downloads/kiwix-hotspot/

This is outdated to my opinion.

**Comment by kelson42** [comment]
@rgaudin Or you have an alternative link to propose?

**Comment by Popolechien** [comment]
Updated (and removed the sentence).

**Comment by rgaudin** [comment]
We do have some (limited) content on the [repo wiki](https://github.com/kiwix/kiwix-hotspot/wiki/FAQ)

**Comment by kelson42** [comment]
@rgaudin Not sure we should link it there. Lets try like it is now. Thx @Popolechien
