### ISSUE TITLE
Improve link to kiwix on wiktionary fr

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#9]
https://fr.wiktionary.org/wiki/Wiktionnaire:Sites_miroirs#Avec_logiciel_.C3.A0_t.C3.A9l.C3.A9charger

Maybe something like this https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Wikip%C3%A9dia_hors-connexion#Kiwix

**Comment by Popolechien** [comment]
Céfé.
