### ISSUE TITLE
Update 404 image

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#91]
![KIWIX_SC-2019_ERROR_RES01-01](https://user-images.githubusercontent.com/21675885/66556649-f0b7d000-eb50-11e9-91f5-16b61b0046df.png)

**Comment by martin8032** [comment]
You don't like my parrot anymore? Probably he's not on brand, is he? ;-)

**Comment by Popolechien** [comment]
I'm all for parrots but I've got a talented @schlagkiwix in the office for three weeks, and believe me I'll squeeze as much as I can out of him (suggestions welcome) :-)

**Comment by martin8032** [comment]
Talented he is indeed!

I just killed a parrot…

https://www.kiwix.org/just-some-non-existing-url
