### ISSUE TITLE
Checksum not available

### ISSUE THREAD

**Issue by Popolechien** [kiwix/web#95]
But as far as I can tell this is only for http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2018-10.zim.md5

**Comment by kelson42** [comment]
yes, we have currently a problem, trying to fix it.

**Comment by kelson42** [comment]
See also https://github.com/kiwix/maintenance/issues/106

**Comment by kelson42** [comment]
The problem has been fixed
