### ISSUE TITLE
Introduce "Privacy policy" page

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#98]
We need a "Privacy policy" page for all our software. Something we can link to from the softwares and from the app stores.

We have one minimum one for Android here:
https://wiki.kiwix.org/wiki/Android_privacy_policy

I would like to have one which is generic (not only for Android) and on the official Web Site. To me, the content can be exactly the same sentence for the moment"
_

> Kiwix does not record nor store any personal information.

_

**Comment by martin8032** [comment]
We already have this for quite a while:

https://www.kiwix.org/en/legal/privacy-policy/

It covers basically the website www.kiwix.org, but it starts with:

«Kiwix software does not record any personal information about its users.»

**Comment by kelson42** [comment]
Wonderful!
