### ISSUE TITLE
Stop letting Google spy on our www.kiwix.org visitors

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#99]
Currently, through the product Google Analytics, our visitors to www.kiwix.org are tracked/spied by Google. In exchange Google partly shared these data with us through web tools which allow us to better understand the dynamics around our Web site.

We have here a privacy problem. This problem is even worse in our case because we advocate our tools as solution to protect privacy. Therefore we basically say something like "privacy matters" and at the same time we sell the private data of our visitors.

The problem is not trivial to fix because Google in exchange provides a service which to some extend is important to us. If a solution to this problem exists, it is probably by finding a (partial) replacement which is reasonable to implement.

This ticket is an attempt to find this alternative and the first thing we need to do here is what service of Google analytics is essential for our organization. I'm not a user of Google Analytics myself, so we should identify the 5 most important features we absolutely need.

**Comment by martin8032** [comment]
Maybe this is something we should discuss in a committee meeting/call and not in this public GitHub repo?

**Comment by kelson42** [comment]
Here is a report about privacy https://privacyscore.org/site/162131/

**Comment by Krinkle** [comment]
It looks like Matomo has been installed at <https://stats.kiwix.org/> and its snippet is loaded on the www.kiwix.org site.

However, Google Analytics is still loaded on top of that currently, and naturally mentioned in the [Privacy policy](https://www.kiwix.org/en/legal/privacy-policy/). Are these ready to be removed?

**Comment by Krinkle** [comment]
Bump.

**Comment by kelson42** [comment]
https://noyb.eu/en/austrian-dsb-eu-us-data-transfers-google-analytics-illegal

**Comment by kelson42** [comment]
https://www.blogdumoderateur.com/cnil-google-analytics-violation-rgpd/

**Comment by martin8032** [comment]
Technically, it's quite simple to replace Google Analytics by a self-hosted Matomo. If we should take this step or not – also with regards to the Google Ad Grants program – is someting we should discuss internally. I'm sure that everybody is aware of the privacy issues which come with Google Analytics.

**Comment by kelson42** [comment]
I would recommend to open an other track for questionning the google ads, which are IMO a problem slightly different.

**Comment by kelson42** [comment]
www.kiwix.org does not use Google Analytics anymore. Problem solved.
